(()=>{const $=id=>document.getElementById(id),E=Workshop.esc;let level=0,p='',b='',s='',found=new Set(),timer=null,seconds=120,complete=false;
const meanings={port:'carry',act:'do or act',form:'shape or form',struct:'build'};
MatchFamilies.forEach((f,i)=>{$('family').insertAdjacentHTML('beforeend',`<option value="${i}">${f.root} · ${meanings[f.root]}</option>`)});
function construct(prefix,base,suffix){let direct=prefix+base+suffix;if(MatchFamilies[level].validCombos.includes(direct))return {word:direct,note:''};if(base.endsWith('e')&&['ing','ed'].includes(suffix)){let changed=prefix+base.slice(0,-1)+suffix;if(MatchFamilies[level].validCombos.includes(changed))return {word:changed,note:`The final e in ${base} is dropped before -${suffix}.`}}return {word:direct,note:''}}
function choices(id,items,type){$(id).innerHTML=items.map(v=>`<button class="btn ${(type==='p'?p:type==='b'?b:s)===v?'primary':''}" data-type="${type}" data-part="${E(v)}" aria-pressed="${(type==='p'?p:type==='b'?b:s)===v}">${E(v||('No '+(type==='p'?'prefix':'suffix')))}</button>`).join('')}
function draw(){const f=MatchFamilies[level];choices('prefixes',['',...Object.keys(f.affixes).filter(x=>f.affixes[x].isPrefix),...f.decoys.filter(x=>!['ly','ive','ment'].includes(x))],'p');choices('bases',[f.root,...found],'b');choices('suffixes',['',...Object.keys(f.affixes).filter(x=>!f.affixes[x].isPrefix),...f.decoys.filter(x=>['ly','ive','ment'].includes(x))],'s');$('construction').textContent=construct(p,b,s).word||'Choose your parts';$('progress').textContent=`${found.size} of ${f.validCombos.length} collected`;$('collection').innerHTML=[...found].map(w=>`<button class="btn" data-base="${E(w)}">${E(w)}</button>`).join('')||'<p class="muted">Your first word will appear here.</p>';$('bank').innerHTML=f.validCombos.map(w=>`<span class="pill">${E(w)}</span>`).join('')}
function pause(){clearInterval(timer);timer=null}
function start(){pause();p='';b=MatchFamilies[level].root;s='';found=new Set();complete=false;$('check').disabled=false;$('feedback').textContent='';$('root-note').textContent=`${b} relates to “${meanings[b]}”. Try a prefix or suffix, then collect the word.`;seconds=120;$('timer').hidden=!$('timed').checked;$('timer').textContent='120 seconds';if($('timed').checked)timer=setInterval(()=>{seconds--;$('timer').textContent=seconds+' seconds';if(seconds<=0){pause();$('feedback').textContent='Challenge time finished. Keep exploring this family without the timer.'}},1000);draw()}
$('check').onclick=()=>{if(complete)return;const built=construct(p,b,s);if(!MatchFamilies[level].validCombos.includes(built.word)){$('feedback').textContent=`${built.word} is not in this activity’s family bank. Try another part, or open the word bank.`;return}if(found.has(built.word)){$('feedback').textContent='Already collected. Try another construction.';return}found.add(built.word);$('feedback').textContent=`Collected ${built.word}. ${built.note} The root ${MatchFamilies[level].root} relates to “${meanings[MatchFamilies[level].root]}”. Use the word in a sentence and explain its meaning.`;if(found.size===MatchFamilies[level].validCombos.length){complete=true;pause();$('check').disabled=true;$('feedback').textContent='Family complete! Download your collection or restart another family.'}draw()};
document.addEventListener('click',e=>{const el=e.target.closest('button');if(!el)return;if(el.dataset.type){const t=el.dataset.type;if(t==='p')p=el.dataset.part;if(t==='b')b=el.dataset.part;if(t==='s')s=el.dataset.part;draw()}if(el.dataset.base){b=el.dataset.base;p=s='';draw()}});
$('clear').onclick=()=>{p=s='';b=MatchFamilies[level].root;draw()};$('hint').onclick=()=>{const f=MatchFamilies[level],prefixes=['',...Object.keys(f.affixes).filter(x=>f.affixes[x].isPrefix)],suffixes=['',...Object.keys(f.affixes).filter(x=>!f.affixes[x].isPrefix)];for(const word of f.validCombos.filter(x=>!found.has(x)))for(const base of [f.root,...found])for(const pre of prefixes)for(const suf of suffixes)if(construct(pre,base,suf).word===word){$('feedback').textContent=`Try ${pre?pre+' + ':''}${base}${suf?' + '+suf:''}. ${construct(pre,base,suf).note}`;return}$('feedback').textContent='Use a collected word as a new base, then add another part.'};$('export').onclick=()=>Workshop.download('morpheme-collection.txt',`Root family: ${MatchFamilies[level].root}\n\n`+[...found].join('\n'));$('restart').onclick=$('timed').onchange=start;$('family').onchange=()=>{level=+$('family').value;start()};document.addEventListener('visibilitychange',()=>{if(document.hidden&&timer){pause();$('feedback').textContent='Timer paused while the page was hidden. Continue at your own pace.'}});start()})();