
(()=>{const $=id=>document.getElementById(id);let angle=0,target=90,index=0,score=0,locked=false,supported=false,wrong=false;const C={x:270,y:270},R=240;
function point(a,r=R){let t=a*Math.PI/180;return {x:C.x+r*Math.cos(t),y:C.y-r*Math.sin(t)}}
for(let a=0;a<=180;a+=5){let p=point(a),q=point(a,R-(a%10?9:17)),line=document.createElementNS('http://www.w3.org/2000/svg','line');for(const [k,v]of Object.entries({x1:p.x,y1:p.y,x2:q.x,y2:q.y,stroke:'#718b80'}))line.setAttribute(k,v);$('ticks').append(line);if(a%10===0){let p=point(a,R-32),t=document.createElementNS('http://www.w3.org/2000/svg','text');t.textContent=a;t.setAttribute('x',p.x);t.setAttribute('y',a===0||a===180?C.y+26:p.y+5);t.setAttribute('text-anchor','middle');t.setAttribute('font-size','13');t.setAttribute('fill','#28493d');$('ticks').append(t)}}
function update(a){if(locked){$('angle-slider').value=angle;return;}angle=Math.round(Math.max(0,Math.min(180,a)));let p=point(angle);$('arm').setAttribute('x2',p.x);$('arm').setAttribute('y2',p.y);$('handle').setAttribute('cx',p.x);$('handle').setAttribute('cy',p.y);$('handle').setAttribute('aria-valuenow',angle);$('angle-slider').value=angle;let end=point(angle,60);$('arc').setAttribute('d',`M270 270 L330 270 A60 60 0 0 0 ${end.x} ${end.y} Z`);$('live').textContent=$('measure').checked?`Current measurement: ${angle}°`:'Live measurement hidden. Use the protractor scale.';if($('measure').checked)supported=true}
function start(){if(index>=8){locked=true;$('progress').textContent='Round complete';$('feedback').textContent=`You built all 8 angles. ${score} were within 2° on the first try without support.`;$('next').hidden=true;$('check').disabled=true;return}locked=false;$('angle-slider').disabled=false;$('handle').setAttribute('aria-disabled','false');supported=false;wrong=false;target=$('level').value==='starter'?(1+Math.floor(Math.random()*17))*10:10+Math.floor(Math.random()*161);$('target').textContent=target+'°';$('progress').textContent=`Angle ${index+1} of 8`;$('feedback').textContent='';$('next').hidden=true;$('check').disabled=false;update(0)}
$('angle-slider').oninput=e=>update(+e.target.value);$('measure').onchange=()=>update(angle);$('handle').onkeydown=e=>{if(['ArrowLeft','ArrowDown','ArrowRight','ArrowUp'].includes(e.key)){e.preventDefault();update(angle+(['ArrowRight','ArrowUp'].includes(e.key)?1:-1))}};
let dragging=false;$('handle').onpointerdown=e=>{if(locked)return;dragging=true;$('handle').setPointerCapture?.(e.pointerId);e.preventDefault()};$('handle').onpointermove=e=>{if(!dragging)return;let r=$('protractor').getBoundingClientRect(),x=(e.clientX-r.left)*540/r.width,y=(e.clientY-r.top)*320/r.height;update(Math.atan2(Math.max(0,C.y-y),x-C.x)*180/Math.PI)};$('handle').onpointerup=$('handle').onpointercancel=()=>dragging=false;
$('check').onclick=()=>{if(locked)return;let diff=Math.abs(target-angle);if(diff<=2){locked=true;$('angle-slider').disabled=true;$('handle').setAttribute('aria-disabled','true');if(!wrong&&!supported)score++;$('feedback').textContent=`You set ${angle}°. The target is ${target}° — within ${diff}°. Read from the baseline on the right.`;$('next').hidden=false;$('check').disabled=true}else{wrong=true;$('feedback').textContent=`You set ${angle}°. ${angle<target?'Increase':'Decrease'} the angle by about ${diff}°. Keep the vertex and baseline fixed.`}};
$('hint').onclick=()=>{supported=true;$('feedback').textContent=target<90?'This is acute: place the arm between the right-hand baseline and 90°.':target===90?'A right angle points straight up at 90°.':'This is obtuse: place the arm between 90° and the left-hand baseline.'};$('next').onclick=()=>{if(!locked)return;index++;start()};$('restart').onclick=$('level').onchange=()=>{index=0;score=0;start()};start();
})();