
(()=>{'use strict';const $=id=>document.getElementById(id),{mapData,quests}=LOCAL_PLACES;let mode='welcome',index=0,round=[],locked=false,first=0,attempted=false,hinted=false,labels=false;
const map=L.map('map').setView([58,-98],4);addSchoolBasemap(map);const markers=new Map();
mapData.forEach(item=>{const m=L.circleMarker(item.coords,{radius:item.type==='community'?8:11,color:{community:'#087c89',city:'#7152ae',region:'#b64382'}[item.type],fillOpacity:.8,weight:2}).addTo(map);m.bindTooltip(item.name);m.on('click',()=>choose(item));m.on('add',()=>accessible(m,item));markers.set(item.name,m);const b=document.createElement('button');b.className='chip';b.textContent=item.name;b.addEventListener('click',()=>choose(item));$('places').append(b);accessible(m,item)});
function accessible(m,item){const e=m.getElement?.();if(!e)return;e.setAttribute('tabindex','0');e.setAttribute('role','button');e.setAttribute('aria-label',item.name);e.addEventListener('keydown',ev=>{if(ev.key==='Enter'||ev.key===' '){ev.preventDefault();choose(item)}})}
mapData.filter(x=>x.type==='community').forEach(x=>{const o=document.createElement('option');o.value=o.textContent=x.name;$('community').append(o)});
function view(target){const x=mapData.find(p=>p.name===target);if(!x)return;map.flyTo(x.type==='community'?[53.29,-113.75]:[58,-98],x.type==='community'?9:3,{duration:.5});}
function display(){locked=false;attempted=false;hinted=false;$('next').hidden=true;$('info').hidden=true;$('feedback').textContent='';$('hint').hidden=false;
if(index>=round.length){mode='done';$('mission-title').textContent='Journey complete';$('mission').textContent=`You located ${round.length} places. ${first} were found on the first try without a hint. Explore freely or start another journey.`;$('progress').textContent=`${round.length} / ${round.length} complete`;$('hint').hidden=true;return}
$('mission-title').textContent='Find the next place';$('mission').innerHTML=round[index].instruction;$('progress').textContent=`Place ${index+1} of ${round.length} · ${index} found`;view(round[index].target)}
function info(item){$('info').hidden=false;$('place-name').textContent=item.name;$('story').textContent=item.story;$('credit').textContent=item.image?item.attribution||'':'';$('photo').hidden=!item.image;$('photo').alt=`${item.name} — original reference photograph`;$('photo').onerror=()=>{$('photo').hidden=true;$('credit').textContent='Photo unavailable. Read the place story above.'};if(item.image)$('photo').src=item.image}
function choose(item){if(mode==='explore'||mode==='done'){info(item);markers.get(item.name).openTooltip();return}if(mode!=='challenge'||locked)return;
if(item.name===round[index].target){locked=true;if(!attempted&&!hinted)first++;$('feedback').textContent=`Found it: ${item.name}. Read about the place, then choose Next.`;$('next').hidden=false;$('hint').hidden=true;info(item);markers.get(item.name).setStyle({fillColor:'#11aa73',color:'#077c52'});$('progress').textContent=`${index+1} of ${round.length} places found`}
else{attempted=true;$('feedback').textContent=`That is ${item.name}. Use the clue and try another marker; your place in the journey stays the same.`}}
$('start').onclick=()=>{mode='challenge';index=0;first=0;round=quests.filter(q=>q.target!==$('community').value);markers.forEach((m,n)=>m.setStyle({fillColor:{community:'#087c89',city:'#7152ae',region:'#b64382'}[mapData.find(x=>x.name===n).type]}));display()};
$('explore').onclick=()=>{mode='explore';$('mission-title').textContent='Explore Canada';$('mission').textContent='Choose a marker or a place from the list. Read the story and compare locations.';$('progress').textContent='Explore mode';$('next').hidden=$('hint').hidden=true;$('feedback').textContent='';$('info').hidden=true;map.setView([58,-98],4)};
$('restart').onclick=()=>{$('start').click()};$('next').onclick=()=>{if(!locked)return;index++;display()};
$('hint').onclick=()=>{if(mode!=='challenge'||locked)return;hinted=true;const item=mapData.find(x=>x.name===round[index].target);$('feedback').textContent=`Look for a ${item.type} marker near ${Math.abs(item.coords[0]).toFixed(1)}° N, ${Math.abs(item.coords[1]).toFixed(1)}° W. You can also use the place list.`;map.flyTo(item.coords,item.type==='community'?11:5,{duration:.5})};
$('labels').onclick=()=>{labels=!labels;$('labels').setAttribute('aria-pressed',String(labels));$('labels').textContent=labels?'Hide place names':'Show place names';markers.forEach(m=>labels?m.openTooltip():m.closeTooltip())};$('overview').onclick=()=>map.setView([58,-98],4);
})();