/* Credited real photographs for landmark recognition. */
window.ROME_BUILDINGS = [
  {
    "id": "colosseum",
    "city": "Rome",
    "name": "Colosseum",
    "location": "Piazza del Colosseo · Ancient Rome",
    "query": "Colosseum Rome",
    "hint": "It was built for huge crowds watching public spectacles.",
    "spot": "An enormous curved wall with stacked rows of arches. Part of the outer wall is missing, revealing the structure inside.",
    "fact": "The amphitheatre opened in AD 80 under Emperor Titus. Its repeated arches helped make a vast arena practical as well as impressive.",
    "source": "https://www.turismoroma.it/en/node/1155",
    "image": "assets/building-01.webp",
    "photo": {
      "title": "File:Colosseum of Rome and Roman forum.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Colosseum_of_Rome_and_Roman_forum.jpg",
      "author": "Wilfredor",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "width": 1100,
      "height": 651
    }
  },
  {
    "id": "pantheon",
    "city": "Rome",
    "name": "Pantheon",
    "location": "Piazza della Rotonda · Your Thursday walk",
    "query": "Pantheon Rome",
    "hint": "Behind this temple-like entrance is a huge circular room with an opening to the sky.",
    "spot": "A triangular pediment over a deep porch of tall columns. The Latin inscription across the front includes the name AGRIPPA.",
    "fact": "This ancient Roman building became a church in 609. Step inside and look up: the round opening in the dome is the oculus.",
    "source": "https://www.turismoroma.it/en/places/pantheon",
    "image": "assets/building-02.webp",
    "photo": {
      "title": "File:Façade of the Pantheon, Rome, Italy.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Fa%C3%A7ade_of_the_Pantheon,_Rome,_Italy.jpg",
      "author": "Julian Lupyan",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "width": 1100,
      "height": 755
    }
  },
  {
    "id": "basilica",
    "city": "Rome",
    "name": "St. Peter’s Basilica",
    "location": "Piazza San Pietro · Vatican City",
    "query": "Saint Peter Basilica Vatican City",
    "hint": "You will find it at one end of the Vatican’s great square.",
    "spot": "A very wide front with monumental columns and statues along the roof. Its enormous dome rises behind the façade.",
    "fact": "Michelangelo designed the great dome, which was completed after his death by Giacomo della Porta and Domenico Fontana.",
    "source": "https://www.basilicasanpietro.va/en/san-pietro/the-dome",
    "image": "assets/building-03.webp",
    "photo": {
      "title": "File:Basilica Sancti Petri blue hour.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Basilica_Sancti_Petri_blue_hour.jpg",
      "author": "Jebulon",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "width": 1100,
      "height": 784
    }
  },
  {
    "id": "castle",
    "city": "Rome",
    "name": "Castel Sant’Angelo",
    "location": "Beside the Tiber · Close to Prati",
    "query": "Castel Sant Angelo Rome",
    "hint": "It began as an emperor’s tomb, then became a fortress.",
    "spot": "A massive round drum with smaller structures above it. Look for the angel on top and the nearby bridge across the Tiber.",
    "fact": "Hadrian commissioned it as a mausoleum for himself and his family. The elevated Passetto di Borgo connects it with the Vatican.",
    "source": "https://www.turismoroma.it/en/places/mausoleum-hadrian-saint-angel-castle",
    "image": "assets/building-04.webp",
    "photo": {
      "title": "File:StAngelo Bridge Rome.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:StAngelo_Bridge_Rome.jpg",
      "author": "AngMoKio",
      "license": "CC BY-SA 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
      "width": 1100,
      "height": 649
    }
  },
  {
    "id": "vittoriano",
    "city": "Rome",
    "name": "Vittoriano",
    "location": "Piazza Venezia · Central Rome",
    "query": "Vittoriano Piazza Venezia Rome",
    "hint": "Its bright stone and enormous size have earned it the nickname “wedding cake.”",
    "spot": "Bright white stone, broad staircases, a sweeping colonnade, and bronze chariots high above either end. A large horse-and-rider statue stands in front.",
    "fact": "It honours Vittorio Emanuele II and Italian unification. The monument was inaugurated in 1911, although construction continued afterwards.",
    "source": "https://www.turismoroma.it/en/places/monument-vittorio-emanuele-ii-vittoriano",
    "image": "assets/building-05.webp",
    "photo": {
      "title": "File:Piazza Venezia - Il Vittoriano (cropped).jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Piazza_Venezia_-_Il_Vittoriano_(cropped).jpg",
      "author": "Paolo Costa Baldi",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "width": 1100,
      "height": 724
    }
  },
  {
    "id": "agnese",
    "city": "Rome",
    "name": "Sant’Agnese in Agone",
    "location": "Piazza Navona · Your Saturday square",
    "query": "Sant Agnese in Agone Piazza Navona Rome",
    "hint": "This church looks onto the long square with Bernini’s Fountain of the Four Rivers.",
    "spot": "A high dome between twin bell towers, with a front that curves inward. It faces directly onto Piazza Navona.",
    "fact": "Work on the present church began in 1652. Borromini reshaped its design, including the curved façade that helps make it so distinctive.",
    "source": "https://www.turismoroma.it/it/luoghi/chiesa-di-santagnese-agone",
    "image": "assets/building-06.webp",
    "photo": {
      "title": "File:Sant Agnese in Agone.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Sant_Agnese_in_Agone.jpg",
      "author": "Chris Nyborg",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "width": 800,
      "height": 562
    }
  },
  {
    "id": "trinita",
    "city": "Rome",
    "name": "Trinità dei Monti",
    "location": "Above the Spanish Steps · Your Thursday walk",
    "query": "Trinita dei Monti church Rome",
    "hint": "Look up from Piazza di Spagna: this church is at the top of the famous staircase.",
    "spot": "Two matching bell towers flank a pale church front. Its elevated position above the Spanish Steps is the easiest location clue.",
    "fact": "This is one of Rome’s French-speaking Catholic churches. Its twin bell towers make it a useful landmark above Piazza di Spagna.",
    "source": "https://www.turismoroma.it/en/places/church-santissima-trinit%C3%A0-dei-monti",
    "image": "assets/building-07.webp",
    "photo": {
      "title": "File:Trinità dei Monti (Rome).jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Trinit%C3%A0_dei_Monti_(Rome).jpg",
      "author": "Kaga tau",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1038,
      "height": 1100
    }
  },
  {
    "id": "senatorio",
    "city": "Rome",
    "name": "Palazzo Senatorio",
    "location": "Piazza del Campidoglio · Capitoline Hill",
    "query": "Palazzo Senatorio Rome",
    "hint": "This civic palace stands at the far end of the square on the Capitoline Hill.",
    "spot": "A central clock tower rises above a symmetrical palace. Two staircases curve up to the entrance from opposite sides.",
    "fact": "Michelangelo’s plan for the Capitoline buildings included the double staircase. Rome’s Municipal Council has met here since 1870.",
    "source": "https://www.turismoroma.it/en/places/palazzo-senatorio",
    "image": "assets/building-08.webp",
    "photo": {
      "title": "File:Campidoglio (Palacio Senatorio) September 2015-1.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Campidoglio_(Palacio_Senatorio)_September_2015-1.jpg",
      "author": "Alvesgaspar",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1100,
      "height": 766
    }
  },
  {
    "id": "duomo",
    "city": "Florence",
    "name": "Florence Cathedral",
    "location": "Piazza del Duomo · Santa Maria del Fiore",
    "query": "Cathedral Santa Maria del Fiore Florence",
    "hint": "Its enormous red dome dominates the skyline of Firenze.",
    "spot": "A huge red-tiled dome divided by pale ribs. Elsewhere on the building, look for patterned white, green, and pink marble.",
    "fact": "Brunelleschi’s dome was built from 1420 to 1436. Its innovative double shell avoided the traditional timber centring used to support a dome during construction.",
    "source": "https://www.feelflorence.it/en/points-interest/brunelleschis-dome",
    "image": "assets/building-09.webp",
    "photo": {
      "title": "File:Dome of Santa Maria del Fiore, Florence, Italy.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Dome_of_Santa_Maria_del_Fiore,_Florence,_Italy.jpg",
      "author": "Julian Lupyan",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "width": 1100,
      "height": 735
    }
  },
  {
    "id": "vecchio",
    "city": "Florence",
    "name": "Palazzo Vecchio",
    "location": "Piazza della Signoria · Your Florence walk",
    "query": "Palazzo Vecchio Florence",
    "hint": "This palace has been a seat of Florentine government for more than seven centuries.",
    "spot": "A sturdy stone palace with battlements along the roof and a very tall, narrow clock tower. Its outline resembles a fortress.",
    "fact": "Palazzo Vecchio overlooks Piazza della Signoria. Behind the severe exterior are elaborate ceremonial rooms, including the vast Salone dei Cinquecento.",
    "source": "https://www.feelflorence.it/en/points-interest/palazzo-vecchio-monumental-rooms",
    "image": "assets/building-10.webp",
    "photo": {
      "title": "File:Piazza della signoria, palazzo vecchio, veduta 01.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Piazza_della_signoria,_palazzo_vecchio,_veduta_01.jpg",
      "author": "Francesco Bini",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1021,
      "height": 1100
    }
  },
  {
    "id": "nuovo",
    "city": "Naples",
    "name": "Castel Nuovo",
    "location": "Via Vittorio Emanuele III · Naples",
    "query": "Castel Nuovo Naples",
    "hint": "It is also known as the Maschio Angioino.",
    "spot": "Large dark round towers with projecting battlements. A pale sculpted triumphal arch forms a striking entrance between two towers.",
    "fact": "The castle served as a royal residence before becoming a fortress under Aragonese rule. Its surviving Palatine Chapel recalls the earlier Angevin palace.",
    "source": "https://www.italia.it/en/campania/naples/castel-nuovo-maschio-angioino",
    "image": "assets/building-11.webp",
    "photo": {
      "title": "File:Castel Nuovo (Maschio Angioino), Façade, Naples (5256).jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Castel_Nuovo_(Maschio_Angioino),_Fa%C3%A7ade,_Naples_(5256).jpg",
      "author": "Marco Ober",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1100,
      "height": 732
    }
  },
  {
    "id": "royal",
    "city": "Naples",
    "name": "Royal Palace of Naples",
    "location": "Piazza del Plebiscito · Naples",
    "query": "Royal Palace of Naples Piazza del Plebiscito",
    "hint": "You will find this long palace facing one of Naples’ largest squares.",
    "spot": "A long, symmetrical façade with rows of windows and statues in niches at ground level. It faces across Piazza del Plebiscito.",
    "fact": "The palace complex dates back to 1600. Today it contains historic royal apartments, courtyards, gardens, and cultural institutions.",
    "source": "https://www.italia.it/en/campania/naples/royal-palace-naples",
    "image": "assets/building-12.webp",
    "photo": {
      "title": "File:Royal Palace (Naples) - Facade.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Royal_Palace_(Naples)_-_Facade.jpg",
      "author": "PaestumPaestum",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "width": 1100,
      "height": 713
    }
  },
  {
    "id": "trevi",
    "city": "Rome",
    "name": "Trevi Fountain",
    "location": "Piazza di Trevi",
    "query": "Trevi Fountain Rome Italy",
    "hint": "A monumental fountain fills the front of a palace.",
    "spot": "Look for the broad pool, rocky sculpted setting, and large central figure beneath a palace façade.",
    "fact": "Rome turned water into a public spectacle here: the fountain’s design competition began in 1732.",
    "source": "https://turismoroma.it/en/places/trevi-fountain",
    "image": "assets/place-trevi.webp",
    "photo": {
      "title": "File:Trevi Fountain - Roma.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Trevi_Fountain_-_Roma.jpg",
      "author": "NikonZ7II",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 542
    }
  },
  {
    "id": "spanish",
    "city": "Rome",
    "name": "Spanish Steps",
    "location": "Piazza di Spagna",
    "query": "Spanish Steps Rome Italy",
    "hint": "A broad staircase climbs toward a church with twin towers.",
    "spot": "The flights divide and join again as they rise. The boat-shaped fountain sits at the bottom.",
    "fact": "Francesco De Sanctis designed the staircase in the 1720s to connect Piazza di Spagna with the hillside above.",
    "source": "https://www.turismoroma.it/en/places/spanish-steps",
    "image": "assets/place-spanish.webp",
    "photo": {
      "title": "File:Piazza di Spagna (Rome) 0004.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Piazza_di_Spagna_(Rome)_0004.jpg",
      "author": "Arnaud 25",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "width": 750,
      "height": 1000
    }
  },
  {
    "id": "forum",
    "city": "Rome",
    "name": "Roman Forum",
    "location": "Between the Capitoline and Palatine hills",
    "query": "Roman Forum Rome Italy",
    "hint": "Think of a ruined city centre rather than a single building.",
    "spot": "Look for a spread of temple columns, ancient paving, arches, and brick ruins in a valley.",
    "fact": "This was a centre of Roman political, religious, commercial, and judicial life.",
    "source": "https://colosseo.it/en/area/the-roman-forum/",
    "image": "assets/place-forum.webp",
    "photo": {
      "title": "File:Foro Romano Musei Capitolini Roma.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Foro_Romano_Musei_Capitolini_Roma.jpg",
      "author": "This Photo was taken by Wolfgang Moroder.  \n\nFeel free to use my photos, but please mention me as the author and send me a  message. \n\n\n\nThis image is not in the public domain. Please respect the copyright protection. It may only be used according to the rules mentioned here. This specifically excludes use in social media, if applicable terms of the licenses listed here not appropriate.\n\n\n\nPlease do not upload an updated image here without consultation with the Author. The author would like to make corrections only at his own source. This ensures that the changes are preserved.Please if you think that any changes should be required, please inform the author.Otherwise you can upload a new image with a new name. Please use one of the templates derivative or extract.",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "width": 1000,
      "height": 411
    }
  },
  {
    "id": "navona",
    "city": "Rome",
    "name": "Piazza Navona",
    "location": "Central Rome",
    "query": "Piazza Navona Rome Italy",
    "hint": "The long square has an obelisk rising above its central fountain.",
    "spot": "Look along the unusually long, narrow space and find the fountain with an Egyptian obelisk.",
    "fact": "The square follows the shape of Domitian’s ancient stadium. Bernini’s Fountain of the Four Rivers stands in its centre.",
    "source": "https://www.turismoroma.it/en/places/navona-square",
    "image": "assets/place-navona.webp",
    "photo": {
      "title": "File:Piazza Navona (Rome) at night.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Piazza_Navona_(Rome)_at_night.jpg",
      "author": "NikonZ7II",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 708
    }
  },
  {
    "id": "maggiore",
    "city": "Rome",
    "name": "Santa Maria Maggiore",
    "location": "Piazza di Santa Maria Maggiore · Esquiline",
    "query": "Santa Maria Maggiore Rome Italy",
    "hint": "A tall brick bell tower stands beside a broad, grand church front.",
    "spot": "Look for the loggia above the entrance and the slender bell tower with rows of small arched openings.",
    "fact": "Santa Maria Maggiore is one of Rome’s four papal basilicas.",
    "source": "https://www.turismoroma.it/en/node/712",
    "image": "assets/place-maggiore.webp",
    "photo": {
      "title": "File:Basilica di Santa Maria Maggiore - Roma.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Basilica_di_Santa_Maria_Maggiore_-_Roma.jpg",
      "author": "NikonZ7II",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 776
    }
  },
  {
    "id": "lateran",
    "city": "Rome",
    "name": "St. John Lateran",
    "location": "Piazza di San Giovanni in Laterano",
    "query": "St. John Lateran Rome Italy",
    "hint": "Large white statues line the top of this imposing church façade.",
    "spot": "Look for the giant columns, central pediment, and rooftop row of saints, with Christ in the centre.",
    "fact": "This is Rome’s cathedral: the cathedral church of the Bishop of Rome, the pope.",
    "source": "https://www.italia.it/en/lazio/rome/basilica-of-saint-john-lateran",
    "image": "assets/place-lateran.webp",
    "photo": {
      "title": "File:San Giovanni in Laterano 2021.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:San_Giovanni_in_Laterano_2021.jpg",
      "author": "NikonZ7II",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 749
    }
  },
  {
    "id": "trastevere",
    "city": "Rome",
    "name": "Santa Maria in Trastevere",
    "location": "Piazza di Santa Maria in Trastevere",
    "query": "Santa Maria in Trastevere Rome Italy",
    "hint": "A modest church front and brick tower overlook a neighbourhood square.",
    "spot": "Look for the mosaic strip high on the façade, the entrance portico, and the tall Romanesque bell tower.",
    "fact": "The church is especially known for its medieval mosaics. Its square is a familiar meeting place in Trastevere.",
    "source": "https://www.turismoroma.it/en/places/basilica-santa-maria-trastevere",
    "image": "assets/place-trastevere.webp",
    "photo": {
      "title": "File:01 Santa Maria in Trastevere Facade.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:01_Santa_Maria_in_Trastevere_Facade.jpg",
      "author": "NateBergin",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "constantine",
    "city": "Rome",
    "name": "Arch of Constantine",
    "location": "Beside the Colosseum",
    "query": "Arch of Constantine Rome Italy",
    "hint": "There are three passageways beneath a block covered in carved reliefs.",
    "spot": "One large central arch is flanked by two smaller arches. Statues and relief panels fill the upper section.",
    "fact": "Dedicated in AD 315, the arch commemorates Constantine’s victory at the Milvian Bridge in AD 312.",
    "source": "https://www.turismoroma.it/en/places/arch-costantine",
    "image": "assets/place-constantine.webp",
    "photo": {
      "title": "File:Arch of Constantine (Rome) - South side, from Via triumphalis.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Arch_of_Constantine_(Rome)_-_South_side,_from_Via_triumphalis.jpg",
      "author": "NikonZ7II (Paris Orlando)",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 844
    }
  },
  {
    "id": "trajan",
    "city": "Rome",
    "name": "Trajan’s Column",
    "location": "Trajan’s Forum · near Piazza Venezia",
    "query": "Trajan’s Column Rome Italy",
    "hint": "A carved story spirals all the way around this tall column.",
    "spot": "Look for the continuous spiral band of reliefs, a square base, and a statue at the top.",
    "fact": "Erected in AD 113, the column depicts Trajan’s campaigns in Dacia. The statue now on top is St. Peter.",
    "source": "https://www.turismoroma.it/en/places/trajan%E2%80%99s-column",
    "image": "assets/place-trajan.webp",
    "photo": {
      "title": "File:Trajan's Column HD.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Trajan%27s_Column_HD.jpg",
      "author": "Livioandronico2013",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 429,
      "height": 1000
    }
  },
  {
    "id": "caracalla",
    "city": "Rome",
    "name": "Baths of Caracalla",
    "location": "Viale delle Terme di Caracalla",
    "query": "Baths of Caracalla Rome Italy",
    "hint": "The enormous brick walls are the remains of a bath complex.",
    "spot": "Look for towering reddish walls and huge broken arches surrounding wide open spaces.",
    "fact": "Imperial baths served more than bathing: people could exercise, study, and socialise in the complex.",
    "source": "https://www.italia.it/en/lazio/rome/baths-of-caracalla",
    "image": "assets/place-caracalla.webp",
    "photo": {
      "title": "File:Baths of Caracalla, facing Caldarium.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Baths_of_Caracalla,_facing_Caldarium.jpg",
      "author": "Ethan Doyle White",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 598
    }
  },
  {
    "id": "ponte",
    "city": "Florence",
    "name": "Ponte Vecchio",
    "location": "Across the Arno",
    "query": "Ponte Vecchio Florence Italy",
    "hint": "Shops appear to cling to the sides of this bridge.",
    "spot": "Look for three low river arches, small shops above them, and buildings projecting beyond the bridge’s edges.",
    "fact": "The present bridge dates to 1345. The Vasari Corridor runs above its shops.",
    "source": "https://www.feelflorence.it/en/points-interest/ponte-vecchio",
    "image": "assets/place-ponte.webp",
    "photo": {
      "title": "File:Ponte Vecchio from Ponte alle Grazie.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Ponte_Vecchio_from_Ponte_alle_Grazie.jpg",
      "author": "Ingo Mehling",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 557
    }
  },
  {
    "id": "baptistery",
    "city": "Florence",
    "name": "Florence Baptistery",
    "location": "Piazza San Giovanni · beside the Duomo",
    "query": "Florence Baptistery Florence Italy",
    "hint": "This separate, eight-sided building wears green-and-white marble.",
    "spot": "Look for the octagonal shape and low pyramidal roof. It is much shorter than the cathedral and bell tower beside it.",
    "fact": "The celebrated bronze doors include Ghiberti’s work. The original doors are in the cathedral museum; copies stand outside.",
    "source": "https://www.feelflorence.it/en/points-interest/san-giovanni-baptistery",
    "image": "assets/place-baptistery.webp",
    "photo": {
      "title": "File:Baptistery, Florence.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Baptistery,_Florence.jpg",
      "author": "Bradley  Weber",
      "license": "CC BY 2.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
      "width": 1000,
      "height": 820
    }
  },
  {
    "id": "giotto",
    "city": "Florence",
    "name": "Giotto’s Bell Tower",
    "location": "Piazza del Duomo",
    "query": "Giotto’s Bell Tower Florence Italy",
    "hint": "A tall, square tower stands separately beside Florence’s cathedral.",
    "spot": "Look for the green, pink, and white marble panels and the large arched windows near the flat-topped summit.",
    "fact": "Giotto designed the cathedral’s bell tower in the fourteenth century.",
    "source": "https://www.feelflorence.it/en/points-interest/giottos-bell-tower",
    "image": "assets/place-giotto.webp",
    "photo": {
      "title": "File:CampanileGiotto-01.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:CampanileGiotto-01.jpg",
      "author": "Thermos",
      "license": "CC BY-SA 2.5",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.5",
      "width": 667,
      "height": 1000
    }
  },
  {
    "id": "croce",
    "city": "Florence",
    "name": "Santa Croce",
    "location": "Piazza Santa Croce",
    "query": "Santa Croce Florence Italy",
    "hint": "A pointed, patterned marble façade faces a broad square.",
    "spot": "Look for the white-and-green geometric front, triangular top, and central star motif beneath it.",
    "fact": "This Franciscan church contains the tombs of Michelangelo, Galileo, and Machiavelli.",
    "source": "https://www.feelflorence.it/en/points-interest/basilica-di-santa-croce",
    "image": "assets/place-croce.webp",
    "photo": {
      "title": "File:Basílica de la Santa Cruz, Florencia, Italia, 2022-09-18, DD 95.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Bas%C3%ADlica_de_la_Santa_Cruz,_Florencia,_Italia,_2022-09-18,_DD_95.jpg",
      "author": "Diego Delso",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 1000
    }
  },
  {
    "id": "novella",
    "city": "Florence",
    "name": "Santa Maria Novella",
    "location": "Piazza Santa Maria Novella",
    "query": "Santa Maria Novella Florence Italy",
    "hint": "Two large curling shapes connect the upper and lower parts of the front.",
    "spot": "Look for the green-and-white marble patterns, circular window, and symmetrical scrolls on either side of the upper façade.",
    "fact": "Leon Battista Alberti completed the façade in the fifteenth century. Inside is Masaccio’s Trinity fresco.",
    "source": "https://www.feelflorence.it/en/points-interest/basilica-di-santa-maria-novella",
    "image": "assets/place-novella.webp",
    "photo": {
      "title": "File:Florence, Santa Maria Novella, facade.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Florence,_Santa_Maria_Novella,_facade.jpg",
      "author": "Armin Kleiner",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 666
    }
  },
  {
    "id": "ovo",
    "city": "Naples",
    "name": "Castel dell’Ovo",
    "location": "Megaride · Naples waterfront",
    "query": "Castel dell’Ovo Naples Italy",
    "hint": "A low fortress sits on a rocky islet right beside the sea.",
    "spot": "Look for massive low walls surrounded by water and joined to the waterfront by a short causeway.",
    "fact": "Its name means “Egg Castle.” The fortress stands on the islet of Megaride.",
    "source": "https://www.italia.it/en/campania/naples/castel-dell-ovo",
    "image": "assets/place-ovo.webp",
    "photo": {
      "title": "File:Castel dell' Ovo.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Castel_dell%27_Ovo.jpg",
      "author": "PaestumPaestum",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 622
    }
  },
  {
    "id": "naples-cathedral",
    "city": "Naples",
    "name": "Naples Cathedral",
    "location": "Via Duomo",
    "query": "Naples Cathedral Naples Italy",
    "hint": "A pale, pointed church front rises above a narrow city street.",
    "spot": "Look for three pointed entrances, a central rose window, and three tall gables across the façade.",
    "fact": "Dedicated to the Assumption of Mary, the cathedral is closely associated with Naples’ patron saint, San Gennaro.",
    "source": "https://www.italia.it/en/campania/naples/things-to-do/naples-city-break",
    "image": "assets/place-naples-cathedral.webp",
    "photo": {
      "title": "File:Naples Cathedral - Duomo di Napoli, Façade (5315-Pan).jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Naples_Cathedral_-_Duomo_di_Napoli,_Fa%C3%A7ade_(5315-Pan).jpg",
      "author": "Marco Ober",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 697,
      "height": 1000
    }
  },
  {
    "id": "paola",
    "city": "Naples",
    "name": "San Francesco di Paola",
    "location": "Piazza del Plebiscito",
    "query": "San Francesco di Paola Naples Italy",
    "hint": "A large dome rises behind a temple-like porch and curved colonnades.",
    "spot": "Look for the broad semicircle of columns embracing the square, with the domed church at its centre.",
    "fact": "The circular, neoclassical church is a landmark of Piazza del Plebiscito.",
    "source": "https://www.italia.it/en/campania/naples/things-to-do/naples-city-break",
    "image": "assets/place-paola.webp",
    "photo": {
      "title": "File:San Francesco di Paola (Naples) exterior.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:San_Francesco_di_Paola_(Naples)_exterior.jpg",
      "author": "PaestumPaestum",
      "license": "CC BY 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
      "width": 1000,
      "height": 415
    }
  },
  {
    "id": "deste",
    "city": "Tivoli",
    "name": "Villa d’Este",
    "location": "Tivoli town centre",
    "query": "Villa d’Este Tivoli Italy",
    "hint": "Terraces and elaborate fountains make the gardens the main clue.",
    "spot": "Look for formal garden paths, descending terraces, pools, and fountains set against the hillside.",
    "fact": "Cardinal Ippolito II d’Este created this Renaissance villa and garden, famous for its elaborate water features.",
    "source": "https://villae.cultura.gov.it/en/the-locations/villa-deste/",
    "image": "assets/place-deste.webp",
    "photo": {
      "title": "File:Villa Deste park Rometta 2011 2.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Villa_Deste_park_Rometta_2011_2.jpg",
      "author": "Karelj",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "width": 1000,
      "height": 686
    }
  },
  {
    "id": "hadrian",
    "city": "Tivoli",
    "name": "Hadrian’s Villa · Maritime Theatre",
    "location": "Villa Adriana · outside Tivoli",
    "query": "Hadrian’s Villa Tivoli Italy",
    "hint": "A round island is surrounded by water and a ring of columns.",
    "spot": "This photograph shows the Maritime Theatre: look for the circular canal around a small island and the curved colonnade.",
    "fact": "Hadrian’s Villa was a vast imperial residence built in the second century AD, with palaces, baths, and gardens.",
    "source": "https://villae.cultura.gov.it/en/the-locations/villa-adriana/",
    "image": "assets/place-hadrian.webp",
    "photo": {
      "title": "File:Villa Hadriana (Villa Adriana Tivoli) 1000 03.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Villa_Hadriana_(Villa_Adriana_Tivoli)_1000_03.jpg",
      "author": "FrDr",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 666
    }
  },
  {
    "id": "vesta",
    "city": "Tivoli",
    "name": "Temple of Vesta, Tivoli",
    "location": "Above the Aniene gorge",
    "query": "Temple of Vesta, Tivoli Tivoli Italy",
    "hint": "A small circular temple stands above a dramatic drop.",
    "spot": "Look for the round stone building and surviving Corinthian columns at the edge of the gorge.",
    "fact": "The temple is traditionally called the Temple of Vesta, although its original dedication is uncertain.",
    "source": "https://www.turismoroma.it/en/places/tivoli",
    "image": "assets/place-vesta.webp",
    "photo": {
      "title": "File:Temple of Vesta (Tivoli) 2017.2.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Temple_of_Vesta_(Tivoli)_2017.2.jpg",
      "author": "Oursana",
      "license": "CC0",
      "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
      "width": 1000,
      "height": 666
    }
  },
  {
    "id": "ostia-theatre",
    "city": "Ostia Antica",
    "name": "Theatre of Ostia Antica",
    "location": "Ostia Antica archaeological park",
    "query": "Theatre of Ostia Antica Ostia Antica Italy",
    "hint": "The stepped seating forms a semicircle, rather than a full oval.",
    "spot": "Look for tiers of stone seats curving around a stage area. Compare that half-circle with an amphitheatre’s complete oval.",
    "fact": "The theatre was built in the late first century BC and enlarged during the Roman imperial period.",
    "source": "https://ostiaantica.cultura.gov.it/en/educational-panels-and-maps/larea-del-teatro/teatro/",
    "image": "assets/place-ostia-theatre.webp",
    "photo": {
      "title": "File:Ostia Theatre.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Ostia_Theatre.jpg",
      "author": "Wikimedia Commons contributor",
      "license": "Public domain",
      "licenseUrl": "https://commons.wikimedia.org/wiki/Commons:Licensing",
      "width": 1000,
      "height": 666
    }
  },
  {
    "id": "ostia-capitolium",
    "city": "Ostia Antica",
    "name": "Capitolium of Ostia",
    "location": "Forum · Ostia Antica",
    "query": "Capitolium of Ostia Ostia Antica Italy",
    "hint": "A high staircase climbs to a tall, roofless brick temple.",
    "spot": "Look for the steep front steps, raised platform, and imposing brick walls at the end of the forum.",
    "fact": "Built under Hadrian, this temple honoured Jupiter, Juno, and Minerva. The exposed brick was originally dressed in marble.",
    "source": "https://ostiaantica.cultura.gov.it/en/educational-panels-and-maps/the-central-area-and-the-official-complexes/capitolium/",
    "image": "assets/place-ostia-capitolium.webp",
    "photo": {
      "title": "File:Capitolium Ostia Antica.JPG",
      "source": "https://commons.wikimedia.org/wiki/File:Capitolium_Ostia_Antica.JPG",
      "author": "Livioandronico2013",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "width": 1000,
      "height": 750
    }
  },
  {
    "id": "pompeii-forum",
    "city": "Pompeii",
    "name": "Forum of Pompeii",
    "location": "Pompeii archaeological park",
    "query": "Forum of Pompeii Pompeii Italy",
    "hint": "A broad ancient square is overlooked by Vesuvius in the distance.",
    "spot": "Look for a long open paved space, surviving columns, and the volcano beyond the temple ruins.",
    "fact": "Pompeii’s forum was the city’s main square, a place for religious ceremonies and decisions about civic life.",
    "source": "https://pompeiisites.org/wp-content/uploads/Pompei-ING-LR-link.pdf",
    "image": "assets/place-pompeii-forum.webp",
    "photo": {
      "title": "File:Forum (Pompeii) and the Vesuvio.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Forum_(Pompeii)_and_the_Vesuvio.jpg",
      "author": "Commonists",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 660
    }
  },
  {
    "id": "pompeii-arena",
    "city": "Pompeii",
    "name": "Amphitheatre of Pompeii",
    "location": "Pompeii archaeological park",
    "query": "Amphitheatre of Pompeii Pompeii Italy",
    "hint": "An entire oval arena is surrounded by stepped seating.",
    "spot": "Look for the complete oval bowl and central open arena. A theatre normally has a semicircle of seats.",
    "fact": "Pompeii’s inhabitants came here to watch public spectacles and combats.",
    "source": "https://pompeiisites.org/wp-content/uploads/Pompei-ING-LR-link.pdf",
    "image": "assets/place-pompeii-arena.webp",
    "photo": {
      "title": "File:Pompeji - Arena.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Pompeji_-_Arena.jpg",
      "author": "No machine-readable author provided. Buckeye~commonswiki assumed (based on copyright claims).",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "width": 1000,
      "height": 750
    }
  },
  {
    "id": "pompeii-apollo",
    "city": "Pompeii",
    "name": "Sanctuary of Apollo, Pompeii",
    "location": "Beside the forum · Pompeii",
    "query": "Sanctuary of Apollo, Pompeii Pompeii Italy",
    "hint": "A temple staircase and columns stand inside a sacred courtyard.",
    "spot": "Look for the central raised temple, surrounding colonnade, and a bronze-coloured statue in the courtyard.",
    "fact": "This sanctuary beside the forum is one of Pompeii’s oldest places of worship.",
    "source": "https://pompeiisites.org/en/excavations-plan-en/sanctuary-of-apollo/",
    "image": "assets/place-pompeii-apollo.webp",
    "photo": {
      "title": "File:Pompeii Temple of Apollo.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Pompeii_Temple_of_Apollo.jpg",
      "author": "Wknight94",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "http://creativecommons.org/licenses/by-sa/3.0/",
      "width": 1000,
      "height": 750
    }
  },
  {
    "id": "pisa-tower",
    "city": "Pisa",
    "name": "Leaning Tower of Pisa",
    "location": "Piazza del Duomo",
    "query": "Leaning Tower of Pisa Pisa Italy",
    "hint": "The white tower’s obvious lean is the giveaway.",
    "spot": "Look for a cylindrical tower wrapped in stacked rings of open arches, tilting away from the vertical.",
    "fact": "The tower is the cathedral’s bell tower, standing separately from the church.",
    "source": "https://www.opapisa.it/en/square-of-miracles/tower/",
    "image": "assets/place-pisa-tower.webp",
    "photo": {
      "title": "File:Italy - Pisa - Leaning Tower.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Italy_-_Pisa_-_Leaning_Tower.jpg",
      "author": "Arne Müseler",
      "license": "CC BY-SA 3.0 de",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/de/deed.en",
      "width": 717,
      "height": 1000
    }
  },
  {
    "id": "pisa-cathedral",
    "city": "Pisa",
    "name": "Pisa Cathedral",
    "location": "Piazza del Duomo",
    "query": "Pisa Cathedral Pisa Italy",
    "hint": "Rows of small arches decorate the front of a long white church.",
    "spot": "Look for the broad marble façade with several stacked galleries, the long nave, and a dome above the crossing.",
    "fact": "The cathedral is the central church of Pisa’s famous Piazza del Duomo ensemble.",
    "source": "https://www.opapisa.it/en/square-of-miracles/cathedral/",
    "image": "assets/place-pisa-cathedral.webp",
    "photo": {
      "title": "File:Pisa - Cattedrale da Battistero 02.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Pisa_-_Cattedrale_da_Battistero_02.jpg",
      "author": "Luca Aless",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 822
    }
  },
  {
    "id": "pisa-baptistery",
    "city": "Pisa",
    "name": "Pisa Baptistery",
    "location": "Piazza del Duomo",
    "query": "Pisa Baptistery Pisa Italy",
    "hint": "This huge circular building has a rounded, pointed dome.",
    "spot": "Look for the round base, lower ring of columns, and ornate pointed arches around the upper level.",
    "fact": "Construction began in 1152. Later builders added Gothic details to the original Romanesque design.",
    "source": "https://www.opapisa.it/en/square-of-miracles/baptistery/",
    "image": "assets/place-pisa-baptistery.webp",
    "photo": {
      "title": "File:CampodeiMiracoliPisa.jpg",
      "source": "https://commons.wikimedia.org/wiki/File:CampodeiMiracoliPisa.jpg",
      "author": "Massimo Catarinella",
      "license": "CC BY-SA 3.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
      "width": 1000,
      "height": 765
    }
  },
  {
    "id": "caserta",
    "city": "Caserta",
    "name": "Royal Palace of Caserta",
    "location": "Piazza Carlo di Borbone",
    "query": "Royal Palace of Caserta Caserta Italy",
    "hint": "An immense rectangular palace is arranged around four courtyards.",
    "spot": "In this aerial view, look for the four internal courts and the long, symmetrical palace frontage.",
    "fact": "Luigi Vanvitelli designed the palace for Charles of Bourbon. Construction began in 1752.",
    "source": "https://reggiadicaserta.cultura.gov.it/en/discover-the-complex/the-royal-palace/",
    "image": "assets/place-caserta.webp",
    "photo": {
      "title": "File:Aerial image of the Palace of Caserta (view from the south).jpg",
      "source": "https://commons.wikimedia.org/wiki/File:Aerial_image_of_the_Palace_of_Caserta_(view_from_the_south).jpg",
      "author": "Carsten Steger",
      "license": "CC BY-SA 4.0",
      "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
      "width": 1000,
      "height": 654
    }
  }
];
