window.DEFAULT_CARDS=[{"term": "Particle model of matter", "definition": "A model that describes matter as tiny particles in constant motion."}, {"term": "Particle", "definition": "A very small constituent of matter, such as an atom or molecule."}, {"term": "Temperature", "definition": "A measure related to the average kinetic energy of particles in a substance."}, {"term": "Heating", "definition": "Transferring thermal energy into a substance."}, {"term": "Cooling", "definition": "Transferring thermal energy out of a substance."}];
(()=>{const $=id=>document.getElementById(id),W=Workshop,key='bgsd-flashcards-v2';let stored=W.load(key,null),cards=DEFAULT_CARDS,known=new Set(),review=new Set(),order=[],index=0,back=false;try{if(stored){cards=CardSets.normalize(stored.cards);known=new Set((stored.known||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<cards.length));review=new Set((stored.review||[]).filter(x=>Number.isInteger(x)&&x>=0&&x<cards.length))}}catch{stored=null}
function save(){if(!W.save(key,{cards,known:[...known],review:[...review]}))$('status').textContent='Storage is unavailable. Export JSON to keep this set.'}
function render(){if(!order.length){$('card').textContent='No cards marked for review yet.';$('card').disabled=true;$('count').textContent='Review is empty';return}let c=cards[order[index]];$('card').disabled=false;$('card').replaceChildren();let text=document.createElement('span');text.textContent=back?c.definition:c.term;$('card').append(text);if(back&&c.imageSrc){let img=document.createElement('img');img.src=c.imageSrc;img.alt='Reference image for '+c.term;img.onerror=()=>img.remove();$('card').append(img)}$('count').textContent=`Card ${index+1} of ${order.length} · ${known.size} known`;$('flip').textContent=back?'Show term':'Show definition';$('card').setAttribute('aria-label',back?'Show term':'Show definition')}
function set(a){order=a;index=0;back=false;render()};function use(a){cards=a;known.clear();review.clear();set(cards.map((_,i)=>i));$('pairs').value=cards.map(c=>c.term+'\n'+c.definition).join('\n\n');save()}
$('card').onclick=$('flip').onclick=()=>{if(!order.length)return;back=!back;render()};$('next').onclick=()=>{if(!order.length)return;index=(index+1)%order.length;back=false;render()};$('previous').onclick=()=>{if(!order.length)return;index=(index-1+order.length)%order.length;back=false;render()};$('know').onclick=()=>{if(!order.length)return;known.add(order[index]);review.delete(order[index]);save();$('next').click()};$('again').onclick=()=>{if(!order.length)return;review.add(order[index]);known.delete(order[index]);save();$('status').textContent='Marked for another practice.';$('next').click()};$('review').onclick=()=>{set([...review]);$('status').textContent=review.size+' cards marked for review.'};$('all').onclick=()=>set(cards.map((_,i)=>i));$('shuffle').onclick=()=>set(W.shuffle(order));$('sample').onclick=()=>use(DEFAULT_CARDS);
$('load').onclick=()=>{try{const a=CardSets.parse($('pairs').value);use(a);$('import-status').textContent=`Loaded ${a.length} cards.`}catch(e){$('import-status').textContent=e.message}};
$('file').onchange=async e=>{let f=e.target.files[0];if(!f)return;try{if(f.size>5*1024*1024)throw Error('Choose a JSON file smaller than 5 MB.');const a=CardSets.normalize(JSON.parse(await f.text()));use(a);$('import-status').textContent=`Imported ${a.length} cards.`}catch(err){$('import-status').textContent=err.message}finally{e.target.value=''}};
$('export').onclick=()=>W.download('flashcards.json',JSON.stringify(cards,null,2),'application/json');$('print').onclick=()=>{$('print-cards').innerHTML=cards.map(c=>'<article class="quiz-item"><h2>'+W.esc(c.term)+'</h2><p>'+W.esc(c.definition)+'</p></article>').join('');window.print()};$('speak').onclick=()=>{if(order.length&&!W.speak(back?cards[order[index]].definition:cards[order[index]].term))$('status').textContent='Reading aloud is unavailable in this browser.'};document.addEventListener('keydown',e=>{if(/INPUT|TEXTAREA|SELECT|BUTTON/.test(e.target.tagName))return;if(e.key==='ArrowRight')$('next').click();else if(e.key==='ArrowLeft')$('previous').click();else if(e.key===' '){e.preventDefault();$('flip').click()}});set(cards.map((_,i)=>i));$('pairs').value=cards.map(c=>c.term+'\n'+c.definition).join('\n\n');
})();