'use strict';const P=PirateMap,$=id=>document.getElementById(id);let mode='compass',trip,player,checkpoint=0,chests=0,moves=0,totalMoves=0,hints=0,roundHints=0,done=false,path=[];
function startVoyage(){chests=0;totalMoves=0;hints=0;startTreasure();}
function startTreasure(){trip=P.journey(mode);player={...trip.start};checkpoint=0;moves=0;roundHints=0;done=false;path=[{...player}];$('feedback').textContent='Plan your direction before you move.';$('feedback').classList.remove('error');render();}
function render(){
 let h='<span class="axis" aria-hidden="true">N↑</span>';for(let x=0;x<P.width;x++)h+=`<span class="axis" aria-hidden="true">${String.fromCharCode(65+x)}</span>`;h+='<span class="ocean" aria-hidden="true"></span>';
 for(let y=0;y<P.height;y++){h+=`<span class="axis" aria-hidden="true">${P.height-y}</span>`;for(let x=0;x<P.width;x++){const p={x,y},isPlayer=P.at(p,player),visit=path.some(s=>P.at(s,p)),found=trip.waypoints.slice(0,checkpoint).some(s=>P.at(s,p));h+=`<button class="cell${isPlayer?' player':visit?' trail visited':''}${found?' found':''}" data-cell="${x},${y}" tabindex="${isPlayer?0:-1}" aria-label="${P.reference(p)}${isPlayer?', your position':''}${found?', checkpoint reached':''}"><span class="position" aria-hidden="true">${P.reference(p)}</span>${isPlayer?'<span aria-hidden="true">◆</span><img class="fox" src="https://cdn.jsdelivr.net/gh/Maltais239/Images@main/piratefox.png" alt="">':''}</button>`;}h+='<span class="ocean" aria-hidden="true"></span>';}
 h+='<span class="ocean" aria-hidden="true"></span>'.repeat(P.width+2);
 $('board').dataset.mode=mode;$('board').innerHTML=h;const fox=$('board').querySelector('.fox');if(fox)fox.onerror=()=>fox.remove();
 $('round-label').textContent=chests>=5?'Voyage complete':`Treasure ${chests+(done?0:1)} of 5`;$('start-reference').textContent=`Begin at ${P.reference(trip.start)}.`;
 $('clues').innerHTML=trip.waypoints.map((p,i)=>{const from=i===0?trip.start:trip.waypoints[i-1];return `<li class="${i<checkpoint?'finished':i===checkpoint?'current':''}"><div class="route-label">${mode==='route'?`Checkpoint ${i+1}`:'Your clue'}</div>${mode==='grid'?`Find ${P.reference(p)}`:P.clues(from,p).join(', then ')}</li>`;}).join('');
 $('position').textContent=`You are at ${P.reference(player)} · ${moves} ${moves===1?'pace':'paces'} this trail`;$('chests').textContent=`${chests} / 5`;$('voyage-stats').textContent=`${totalMoves} paces travelled · ${hints} clues helped`;$('next').hidden=!done||chests>=5;$('reset-route').disabled=done;$('hint').disabled=done;document.querySelectorAll('[data-direction]').forEach(b=>b.disabled=done);document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===mode)));
}
function move(d,focus=false){if(done)return;const next=P.move(player,d);if(P.at(next,player)){$('feedback').classList.add('error');$('feedback').textContent='You reached the edge of this grid. Choose another direction.';return;}player=next;moves++;totalMoves++;path.push({...player});$('feedback').classList.remove('error');
 if(P.at(player,trip.waypoints[checkpoint])){checkpoint++;if(checkpoint===trip.waypoints.length){done=true;chests++;$('feedback').textContent=chests===5?`Voyage complete! You found all five treasures in ${totalMoves} paces. Start a new voyage or try another challenge.`:`Treasure found at ${P.reference(player)}! ${roundHints?'You used a clue to help.':'You followed the trail independently.'} Choose Next treasure when ready.`;}else $('feedback').textContent=`Checkpoint ${checkpoint} reached. Now follow the next clue from ${P.reference(player)}.`;}else $('feedback').textContent=`One pace ${d}. Keep following the current clue.`;
 render();if(focus)$('board').querySelector('.player').focus();}
document.querySelector('.tabs').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b||b.dataset.mode===mode)return;mode=b.dataset.mode;startVoyage();};document.querySelector('.compass').onclick=e=>{const b=e.target.closest('[data-direction]');if(b)move(b.dataset.direction);};
$('board').onkeydown=e=>{const d={ArrowUp:'north',ArrowDown:'south',ArrowLeft:'west',ArrowRight:'east'}[e.key];if(d){e.preventDefault();move(d,true);}};
$('board').onclick=e=>{const b=e.target.closest('[data-cell]');if(!b||done)return;const[x,y]=b.dataset.cell.split(',').map(Number);const dx=x-player.x,dy=y-player.y;if(Math.abs(dx)+Math.abs(dy)!==1){$('feedback').classList.add('error');$('feedback').textContent='Tap one square next to your pirate, or use a direction button.';return;}move(dx===1?'east':dx===-1?'west':dy===1?'south':'north',true);};
$('reset-route').onclick=()=>{if(done)return;player={...trip.start};checkpoint=0;moves=0;path=[{...player}];$('feedback').textContent='Back at the original start. Your clues have not changed.';render();};
$('hint').onclick=()=>{if(done)return;hints++;roundHints++;const t=trip.waypoints[checkpoint];$('feedback').classList.remove('error');$('feedback').textContent=`From where you are now: ${P.clues(player,t).join(', then ')}. Target grid reference: ${P.reference(t)}. North is up; east is right.`;render();};$('next').onclick=()=>{if(done&&chests<5)startTreasure();};$('new-voyage').onclick=startVoyage;startVoyage();
