'use strict';const B=BridgeLab,$=id=>document.getElementById(id),key='bgsd-walker-bridge-v2';let design={type:'beam',material:'timber',span:30,load:40,wind:10,bracing:false,anchors:false,pier:false},scenario=-1;
let record=Studio.read(key,{trials:[],reflection:''});if(!record||!Array.isArray(record.trials))record={trials:[],reflection:''};record.trials=record.trials.filter(t=>t&&B.validate(t.design)).slice(-30).map(t=>({...t,result:B.calculate(t.design)}));$('reflection').value=typeof record.reflection==='string'?record.reflection:'';
function save(){$('save-status').textContent=Studio.save(key,record)?'Trials and reflection saved on this browser.':'Browser storage is unavailable. Download or print to keep your investigation.';}
function diagram(result=null){const bend=result&&!result.meetsLoad?20:0,colour=result&&!result.meetsLoad?'#a5443c':'#c36332';let structure='';if(design.type==='truss'){for(let i=0;i<8;i++){const x=60+i*65;structure+=`<path d="M${x} 185 L${x+32.5} 125 L${x+65} 185" fill="none" stroke="${colour}" stroke-width="5"/>`; }structure+='<path d="M92 125 H548" stroke="'+colour+'" stroke-width="5"/>';}
 if(design.type==='arch')structure=`<path d="M60 190 Q320 15 580 190" fill="none" stroke="${colour}" stroke-width="12"/>`;
 if(design.type==='suspension'){structure=`<path d="M145 185 V70 M495 185 V70" stroke="${colour}" stroke-width="12"/><path d="M60 180 L145 70 Q320 190 495 70 L580 180" fill="none" stroke="${colour}" stroke-width="5"/>`;for(let i=1;i<7;i++){const x=145+i*50,t=i/7,y=70+240*t*(1-t);structure+=`<path d="M${x} ${y} V185" stroke="${colour}" stroke-width="2"/>`;}}
 if(design.bracing)for(let i=0;i<6;i++){const x=65+i*85;structure+=`<path d="M${x} 180 L${x+80} 145 M${x} 145 L${x+80} 180" stroke="#965127" stroke-width="2" opacity=".6"/>`;}
 $('bridge-diagram').innerHTML=`<svg viewBox="0 0 640 300" role="img" aria-label="${B.types[design.type].name} bridge spanning ${design.span} model units${design.pier?', with a centre pier':''}. Test load ${design.load}."><rect width="640" height="300" fill="#edf4f1"/><path d="M0 220 Q180 255 320 227 T640 245 V300 H0 Z" fill="#a3c9d5"/><path d="M0 195 H65 V265 H0 M575 195 H640 V265 H575" fill="#c5b8a0"/>${structure}<path d="M60 185 Q320 ${185+bend} 580 185" stroke="${colour}" stroke-width="${design.type==='beam'?12:8}" fill="none"/>${design.pier?'<path d="M320 190 V267" stroke="#928b77" stroke-width="18"/>':''}${design.anchors?'<path d="M45 180 H78 M560 180 H595" stroke="#806a4b" stroke-width="20"/>':''}<path d="M320 25 V105 M308 88 L320 108 L332 88" fill="none" stroke="#236a96" stroke-width="5"/><text x="336" y="56" font-size="16" fill="#236a96">Load: ${design.load}</text><text x="320" y="290" text-anchor="middle" font-size="15" fill="#35444a">Span: ${design.span} model units</text><text x="18" y="28" font-size="13" fill="#35444a">Wind index: ${design.wind}</text></svg>`;}
function sync(){$('bridge-types').innerHTML=Object.entries(B.types).map(([id,t])=>`<button class="btn" data-type="${id}" aria-pressed="${design.type===id}">${t.name}</button>`).join('');$('material').value=design.material;for(const k of ['span','load','wind']){$(k).value=design[k];$(k+'-value').textContent=design[k];}for(const k of ['bracing','anchors','pier'])$(k).checked=design[k];$('result').hidden=true;diagram();$('feedback').textContent='Design changed. Test it to add evidence to your record.';$('feedback').classList.remove('error');$('scenario-note').hidden=scenario<0;if(scenario>=0){const s=B.scenarios[scenario];$('scenario-note').textContent=`${s.name}: span ${s.span}, load ${s.load}, wind index ${s.wind}, budget ${s.budget} credits. Keep these test conditions fixed while improving your design.`;}}
function renderTrials(){$('trials').innerHTML=record.trials.length?'<table><thead><tr><th>Trial</th><th>Design</th><th>Material</th><th>Span / load / wind</th><th>Capacity</th><th>Cost</th><th>Model result</th></tr></thead><tbody>'+record.trials.map((t,i)=>`<tr><td>${i+1}</td><td>${B.types[t.design.type].name}${t.design.bracing?' + bracing':''}${t.design.anchors?' + end supports':''}${t.design.pier?' + pier':''}</td><td>${B.materials[t.design.material].name}</td><td>${t.design.span} / ${t.design.load} / ${t.design.wind}</td><td>${t.result.capacity}</td><td>${t.result.cost}</td><td>${t.result.meetsLoad?'Meets load':'Below test load'}</td></tr>`).join('')+'</tbody></table>':'<p class="muted">Test your first design, change one feature, then test again.</p>';$('baseline').innerHTML=record.trials.slice(0,-1).map((t,i)=>`<option value="${i}">Trial ${i+1}: ${B.types[t.design.type].name}</option>`).join('');$('baseline').disabled=record.trials.length<2;if(record.trials.length>=2)$('baseline').value=record.trials.length-2;compare();}
function compare(){if(record.trials.length<2){$('comparison').textContent='Two trials will let you compare a change.';return;}const a=record.trials[Number($('baseline').value)],b=record.trials.at(-1),changes=B.changed(a.design,b.design),d=b.result.capacity-a.result.capacity;$('comparison').textContent=`Capacity changed by ${d>0?'+':''}${d} model units; cost changed by ${b.result.cost-a.result.cost} credits. ${changes.length===1?'You changed one variable: '+changes[0]+'.':changes.length===0?'The designs are identical.':'You changed '+changes.join(', ')+'. Change one variable at a time to isolate its effect.'}`;}
$('test').onclick=()=>{const result=B.calculate(design),latest=record.trials.at(-1);if(latest&&B.changed(latest.design,design).length===0){$('feedback').textContent='This design is already your latest trial. Change one feature to investigate its effect.';return;}record.trials.push({design:{...design},result,date:new Date().toISOString()});record.trials=record.trials.slice(-30);$('result').hidden=false;$('result').innerHTML=`<div class="result-heading">${result.meetsLoad?'Meets the test load in this model.':'Below the test load in this model.'}</div><div class="load-readout" style="margin-top:14px"><div><span>Model capacity</span><strong>${result.capacity}</strong></div><div><span>Test load</span><strong>${design.load}</strong></div><div><span>Cost</span><strong>${result.cost}</strong></div></div><p class="small" style="margin-top:12px">${result.margin>=0?result.margin+' capacity units above the load.':Math.abs(result.margin)+' capacity units short of the load.'} Unsupported span: ${result.unsupported}.</p>`;diagram(result);$('feedback').textContent=scenario>=0?(B.meetsScenario(design,result,B.scenarios[scenario])?'The design meets the investigation’s load and budget in this model. Compare it with an earlier trial to explain your choices.':'Check both the required test conditions and budget. Use the trial record to choose one change.'):'Trial recorded. Keep the test conditions the same, change one design feature, then test again.';renderTrials();save();};
$('bridge-types').onclick=e=>{const b=e.target.closest('[data-type]');if(b){design.type=b.dataset.type;sync();}};$('material').innerHTML=Object.entries(B.materials).map(([k,v])=>`<option value="${k}">${v.name}</option>`).join('');$('material').onchange=()=>{design.material=$('material').value;sync();};
for(const k of ['span','load','wind'])$(k).oninput=()=>{design[k]=Number($(k).value);sync();};for(const k of ['bracing','anchors','pier'])$(k).onchange=()=>{design[k]=$(k).checked;sync();};
$('scenario').innerHTML+=B.scenarios.map((s,i)=>`<option value="${i}">${s.name}</option>`).join('');$('scenario').onchange=()=>{scenario=Number($('scenario').value);if(scenario>=0){const s=B.scenarios[scenario];design.span=s.span;design.load=s.load;design.wind=s.wind;}sync();};$('restore').onclick=()=>{if(!record.trials.length){$('feedback').textContent='Record a trial first.';return;}design={...record.trials.at(-1).design};sync();};$('baseline').onchange=compare;$('reflection').oninput=()=>{record.reflection=$('reflection').value;save();};
$('csv').onclick=()=>Studio.download('bridge-investigation.csv',Studio.csv([['Trial',...B.fields,'Capacity','Cost','Meets model load'],...record.trials.map((t,i)=>[i+1,...B.fields.map(k=>t.design[k]),t.result.capacity,t.result.cost,t.result.meetsLoad]),[],['Reflection',record.reflection]]),'text/csv');$('print').onclick=()=>window.print();$('clear').onclick=()=>{if(!confirm('Clear bridge trials and reflection saved on this browser?'))return;record={trials:[],reflection:''};$('reflection').value='';renderTrials();save();};sync();renderTrials();save();
