'use strict';
const C=CoordinateLab,$=id=>document.getElementById(id);let mode='explore',step=30,index=0,round=[],answers=[],done=false,assisted=false,wrong=false,point={lat:30,lon:-90};let map,grid,selection,guide,revealed;let worldView=true,fittingWorld=false;
function world(){if(!map)return;fittingWorld=true;map.fitBounds([[-68,-179],[80,179]],{padding:[16,16],animate:false});fittingWorld=false;worldView=true;}
function drawGrid(){if(!map)return;if(grid)grid.remove();grid=L.layerGroup().addTo(map);const spacing=mode==='challenge'?step:30;const pixelsPerDegree=256*Math.pow(2,map.getZoom())/360;const longitudeLabelStep=[30,60,90,180].find(n=>n*pixelsPerDegree>=54)||180;
 for(let lon=-180;lon<=180;lon+=spacing){L.polyline([[-85,lon],[85,lon]],{color:lon===0?'#855394':'#385a6b',weight:lon===0?2.5:1,opacity:lon===0?.85:.35,interactive:false}).addTo(grid);if(lon>-180&&lon<180&&(spacing>=15||lon%30===0)&&lon%longitudeLabelStep===0)L.marker([72,lon],{icon:L.divIcon({className:'',html:`<span class="coord-label">${C.label(lon,'lon').replace(' (Prime Meridian)','')}</span>`,iconSize:[70,20],iconAnchor:[30,10]}),interactive:false,keyboard:false}).addTo(grid);}
 for(let lat=-60;lat<=60;lat+=spacing){L.polyline([[lat,-180],[lat,180]],{color:lat===0?'#236a96':'#385a6b',weight:lat===0?2.5:1,opacity:lat===0?.85:.35,interactive:false}).addTo(grid);if(spacing>=15||lat%30===0)L.marker([lat,-163],{icon:L.divIcon({className:'',html:`<span class="coord-label">${C.label(lat,'lat').replace(' (Equator)','')}</span>`,iconSize:[65,20],iconAnchor:[30,10]}),interactive:false,keyboard:false}).addTo(grid);}}
function clearAnswer(){if(guide){guide.remove();guide=null;}if(revealed){revealed.remove();revealed=null;}}
function drawPoint(){if(!map)return;if(selection)selection.remove();selection=L.circleMarker([point.lat,point.lon],{radius:8,color:'#fff',weight:2,fillColor:'#236a96',fillOpacity:1}).addTo(map);if(mode==='explore'){clearAnswer();guide=L.layerGroup([L.polyline([[point.lat,-180],[point.lat,180]],{color:'#236a96',weight:3,interactive:false}),L.polyline([[-85,point.lon],[85,point.lon]],{color:'#855394',weight:3,interactive:false})]).addTo(map);}}
function setPoint(p){point=mode==='challenge'?C.snap(p.lat,p.lon,step):p;$('latitude').value=Number(point.lat.toFixed(2));$('longitude').value=Number(point.lon.toFixed(2));drawPoint();if(mode==='explore')$('target').innerHTML=`<span class="latitude">${C.label(point.lat,'lat')}</span><br><span class="longitude">${C.label(point.lon,'lon')}</span>`;else if(!done){$('feedback').classList.remove('error');$('feedback').textContent=`Selected ${C.label(point.lat,'lat')}, ${C.label(point.lon,'lon')}. Check your location when ready.`;}}
function render(){const game=mode==='challenge';$('explore').setAttribute('aria-pressed',String(!game));$('challenge').setAttribute('aria-pressed',String(game));$('challenge-settings').hidden=!game;$('hint').hidden=!game||done;$('reveal').hidden=!game||done;$('next').hidden=!game||!done;$('check').hidden=game&&done;$('check').textContent=game?'Check my location':'Show this location';$('mode-kicker').textContent=game?`Location ${index+1} of 8`:'Explore';$('task').textContent=game?'Find this intersection.':'Pick any point.';if(game)$('target').innerHTML=`<span class="latitude">${C.label(round[index].lat,'lat')}</span><br><span class="longitude">${C.label(round[index].lon,'lon')}</span>`;else setPoint(point);}
function start(){step=Number($('precision').value);round=C.targets(step);index=0;answers=[];$('results').hidden=true;nextQuestion();drawGrid();world();}
function nextQuestion(){done=false;assisted=false;wrong=false;clearAnswer();$('feedback').textContent='Select the latitude first, then the longitude.';$('feedback').classList.remove('error');render();setPoint({lat:0,lon:0});}
function showAnswer(){clearAnswer();if(!map)return;const t=round[index];guide=L.layerGroup([L.polyline([[t.lat,-180],[t.lat,180]],{color:'#d95d3d',weight:3,interactive:false}),L.polyline([[-85,t.lon],[85,t.lon]],{color:'#d95d3d',weight:3,interactive:false})]).addTo(map);revealed=L.circleMarker([t.lat,t.lon],{radius:9,color:'#fff',weight:2,fillColor:'#d95d3d',fillOpacity:1}).addTo(map);}
function complete(correct){if(done)return;done=true;answers.push(correct&&!assisted&&!wrong);showAnswer();$('feedback').classList.remove('error');$('feedback').textContent=(correct?'You found the intersection. ':'Here is where the two coordinates meet. ')+(assisted||wrong?'You used support on this location.':'You found it independently.');render();}
$('check').onclick=()=>{const p=C.validate($('latitude').value,$('longitude').value);if(!p){$('feedback').classList.add('error');$('feedback').textContent='Enter latitude from −85 to 85 and longitude from −180 to 180.';return;}setPoint(p);if(mode==='explore'){$('feedback').textContent=`${C.label(point.lat,'lat')} is the horizontal line; ${C.label(point.lon,'lon')} is the vertical line. Their intersection is your point.`;return;}if(done)return;if(C.same(point,round[index]))complete(true);else{wrong=true;$('feedback').classList.add('error');$('feedback').textContent=C.feedback(point,round[index])+' Try another point.';}};
$('hint').onclick=()=>{if(done)return;assisted=true;if(guide)guide.remove();if(map)guide=L.polyline([[round[index].lat,-180],[round[index].lat,180]],{color:'#d95d3d',weight:3,interactive:false}).addTo(map);$('feedback').textContent='The orange line shows the target latitude. Find the correct longitude along it.';};
$('reveal').onclick=()=>{assisted=true;complete(false);};$('next').onclick=()=>{if(!done)return;index++;if(index>=8){$('mode-kicker').textContent='Round complete';$('task').textContent='Eight locations explored.';$('target').textContent='';$('next').hidden=true;$('results').hidden=false;$('results').innerHTML=`<h2>${answers.filter(Boolean).length} of 8 found independently.</h2><p>You practised ${step}° grid intersections. Try a smaller spacing or explore freely.</p>`;return;}nextQuestion();};
$('explore').onclick=()=>{mode='explore';clearAnswer();$('results').hidden=true;$('feedback').textContent='';render();drawGrid();};$('challenge').onclick=()=>{mode='challenge';start();};$('restart').onclick=start;$('world').onclick=world;
try{if(typeof L==='undefined')throw Error('map library unavailable');map=L.map('map',{minZoom:0,maxZoom:7,zoomSnap:.25,zoomDelta:.5,worldCopyJump:false,maxBounds:[[-85,-180],[85,180]],maxBoundsViscosity:.8});addSchoolBasemap(map);map.on('zoomstart',()=>{if(!fittingWorld)worldView=false;});map.on('dragstart',()=>{worldView=false;});map.on('zoomend',drawGrid);map.on('screenresize',()=>{if(worldView)world();});world();map.on('click',e=>{if(mode==='challenge'&&done)return;setPoint({lat:Math.max(-85,Math.min(85,e.latlng.lat)),lon:C.wrap(e.latlng.lng)});});drawGrid();}catch(e){$('map-notice').textContent='The visual map could not load. The coordinate entry and practice questions still work.';}
render();


Studio.fitWorkspace($('main'),{minHeight:300});
