window.imageSparkGrade7 = [
  {
    "id": "charlottetown",
    "title": "Charlottetown Conference delegates",
    "theme": "Confederation & government",
    "date": "1864",
    "kind": "Photograph",
    "credit": "George P. Roberts / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Charlottetown_Conference_Delegates,_September_1864.JPG",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "State building and the goals of Confederation",
    "inquiry": "How does the way the delegates are arranged communicate authority? Which voices would we need to understand who was excluded?",
    "url": "images/grade7/charlottetown.jpg",
    "era": "Confederation"
  },
  {
    "id": "quebec",
    "title": "Quebec Conference delegates",
    "theme": "Confederation & government",
    "date": "27 October 1864",
    "kind": "Photograph",
    "credit": "Jules I. Livernois / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:QuebecConvention1864.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Quebec Conference and the creation of government",
    "inquiry": "What visible evidence suggests this is a formal political meeting? What cannot this group photograph tell us about their agreements?",
    "url": "images/grade7/quebec.jpg",
    "era": "Confederation"
  },
  {
    "id": "confederation-painting",
    "title": "Fathers of Confederation: a later painting",
    "theme": "Confederation & government",
    "date": "Painting: 1884; depicts 1864",
    "kind": "Painting reproduced in a photograph",
    "credit": "Robert Harris; photograph by James Ashfield / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Fathers_of_Confederation_LAC_c001855.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Confederation and historical perspectives",
    "inquiry": "How does a painting made twenty years later differ from a photograph taken at the time? Compare who is shown and how the room is arranged.",
    "url": "images/grade7/confederation-painting.jpg",
    "era": "Confederation"
  },
  {
    "id": "expansion-cartoon",
    "title": "Canada between Britain and the United States",
    "theme": "Confederation & government",
    "date": "July 1870",
    "kind": "Political cartoon",
    "credit": "Artist not identified in the file record / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:1870_political_cartoon.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Concerns about United States expansion and Canadian sovereignty",
    "inquiry": "What do the child and the two adults symbolize? How does this cartoon try to influence its audience?",
    "url": "images/grade7/expansion-cartoon.jpg",
    "era": "Confederation"
  },
  {
    "id": "commons",
    "title": "Inside the House of Commons",
    "theme": "Confederation & government",
    "date": "24 September 2012",
    "kind": "Contemporary photograph",
    "credit": "Jonathankslim",
    "source": "https://commons.wikimedia.org/wiki/File:House_of_Common,_Parliament_Canada.jpg",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0/",
    "connection": "The legislative branch and representative government",
    "inquiry": "What does the arrangement of seats suggest about how Parliament works? What evidence would you need to explain the roles of the people who sit here?",
    "url": "images/grade7/commons.jpg",
    "era": "Modern Era"
  },
  {
    "id": "metis-government",
    "title": "Métis provisional government at Red River",
    "theme": "Westward expansion & land",
    "date": "1870; believed to be 3 June",
    "kind": "Photograph",
    "credit": "Believed to be Joseph Langevin / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:ProvisionalMetisGovernment.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Red River Conflict and Métis responses to expansion",
    "inquiry": "What visible details communicate leadership and organization? How could this image challenge an account that omits Métis political leadership?",
    "url": "images/grade7/metis-government.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "redriver-map",
    "title": "Red River Territory and early Manitoba",
    "theme": "Westward expansion & land",
    "date": "1870",
    "kind": "Historical map",
    "credit": "E. H. Charles Lionais; University of Manitoba Archives & Special Collections / Manitoba Historical Maps",
    "source": "https://commons.wikimedia.org/wiki/File:Map_of_the_Red_River_Territory_(1870)_(2086983828).jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "connection": "Changing boundaries and the formation of Manitoba",
    "inquiry": "Which boundaries, routes and place names does the map emphasize? Whose relationships to this land are difficult to see on a colonial map?",
    "url": "images/grade7/redriver-map.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "treaty7",
    "title": "Treaty 7: written articles",
    "theme": "Westward expansion & land",
    "date": "22 September 1877",
    "kind": "Treaty document",
    "credit": "Crown treaty document / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Treatyno7.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Numbered treaties, land and governance",
    "inquiry": "Whose legal language is used in this written document? Why should an investigation also include First Nations oral histories and understandings of the treaty?",
    "url": "images/grade7/treaty7.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "metis-scrip",
    "title": "Métis scrip coupon for 160 dollars",
    "theme": "Westward expansion & land",
    "date": "23 June 1894 (printed on coupon)",
    "kind": "Government document",
    "credit": "Department of the Interior; Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Metis_land_scrip_005005-e010836017-v8.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "The scrip system and Métis land claims",
    "inquiry": "What does the coupon promise, and what conditions are printed on it? What other evidence is needed to understand how scrip affected Métis land ownership?",
    "url": "images/grade7/metis-scrip.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "regina-1885",
    "title": "Poundmaker, Big Bear and others at Regina barracks",
    "theme": "Westward expansion & land",
    "date": "1885",
    "kind": "Photograph",
    "credit": "O. B. Buell / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Groupnine-nwmp-regina.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Northwest Resistance, First Nations perspectives and state authority",
    "inquiry": "What can you observe about positioning, clothing and the setting? What additional context is needed before inferring relationships or power from a posed photograph?",
    "url": "images/grade7/regina-1885.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "lastspike",
    "title": "The Last Spike of the Canadian Pacific Railway",
    "theme": "Economy & transportation",
    "date": "7 November 1885",
    "kind": "Photograph",
    "credit": "Alexander Ross / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Donald_A._Smith_driving_the_Last_Spike_to_complete_the_Canadian_Pacific_Railway,_1885.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "connection": "Railway construction, western settlement and the economy",
    "inquiry": "Who receives attention in this ceremony? Compare it with the railway-workers photograph: whose labour becomes visible or invisible?",
    "url": "images/grade7/lastspike.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "railway-workers",
    "title": "Chinese workers building the Canadian Pacific Railway",
    "theme": "Economy & transportation",
    "date": "1884",
    "kind": "Photograph",
    "credit": "Ernest Brown / Library and Archives Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Chinese_at_work_on_C.P.R._(Canadian_Pacific_Railway)_in_Mountains,_1884.jpg",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0/",
    "connection": "Railway labour, immigration and economic development",
    "inquiry": "What details suggest the physical demands of the work? Compare this image with the Last Spike ceremony to examine whose contributions are celebrated.",
    "url": "images/grade7/railway-workers.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "national-policy",
    "title": "Riding into power: the National Policy",
    "theme": "Economy & transportation",
    "date": "28 September 1878",
    "kind": "Political cartoon",
    "credit": "John Wilson Bengough, Grip",
    "source": "https://commons.wikimedia.org/wiki/File:Riding_into_power.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Macdonald’s National Policy and economic decisions",
    "inquiry": "How does the artist use symbols and exaggeration? What claim about the National Policy is being made, and what would you need to test it?",
    "url": "images/grade7/national-policy.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "prairie-wheat",
    "title": "Canada West: a map in a settlement brochure",
    "theme": "Economy & transportation",
    "date": "1916",
    "kind": "Promotional brochure map",
    "credit": "Canada, Department of the Interior / University of Toronto Libraries",
    "source": "https://commons.wikimedia.org/wiki/File:Canada_west_-_350,000,000_bushels_wheat_in_1915_-_Manitoba,_Saskatchewan,_Alberta_(1916)_(14591304049).jpg",
    "license": "No known copyright restrictions",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "connection": "Prairie agriculture, regional economies and immigration promotion",
    "inquiry": "Which places and transport routes are emphasized? How could the brochure’s purpose influence what is shown or left out?",
    "url": "images/grade7/prairie-wheat.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "banknote",
    "title": "Bank of Canada one-dollar note",
    "theme": "Economy & transportation",
    "date": "1935",
    "kind": "Banknote",
    "credit": "Bank of Canada",
    "source": "https://commons.wikimedia.org/wiki/File:Bank_of_Canada_one_dollar_note,_1935.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Banking and the Bank of Canada",
    "inquiry": "Which words, images and symbols communicate trust or authority? What can a banknote show about institutions, and what cannot it tell us about the whole economy?",
    "url": "images/grade7/banknote.jpg",
    "era": "Modern Era"
  },
  {
    "id": "ontario-poster",
    "title": "An invitation to immigrate to Ontario",
    "theme": "Immigration & citizenship",
    "date": "1878",
    "kind": "Government recruitment poster",
    "credit": "Province of Ontario / Archives of Ontario",
    "source": "https://commons.wikimedia.org/wiki/File:Ontario_Immigration_Poster.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Government encouragement of immigration",
    "inquiry": "Who appears to be the intended audience? What opportunities are advertised, and whose experiences or barriers are absent?",
    "url": "images/grade7/ontario-poster.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "ukrainian-homestead",
    "title": "Ukrainian homestead family near Athabasca",
    "theme": "Immigration & citizenship",
    "date": "1920",
    "kind": "Photograph",
    "credit": "Photographer not identified / Provincial Archives of Alberta, A10015",
    "source": "https://commons.wikimedia.org/wiki/File:Ukrainian_homestead_family_in_front_of_Ukrainian-style_house,_Athabasca,_Alberta.jpg",
    "license": "No known copyright restrictions",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "connection": "Ukrainian settlement and prairie communities",
    "inquiry": "What visible details suggest the family’s work, home and adaptation? What would you need to learn from their own accounts before drawing conclusions?",
    "url": "images/grade7/ukrainian-homestead.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "headtax",
    "title": "Don Lee’s Chinese head-tax certificate",
    "theme": "Immigration & citizenship",
    "date": "2 August 1918",
    "kind": "Immigration document",
    "credit": "Citizenship and Immigration Canada; Vancouver Public Library, VPL 30625",
    "source": "https://commons.wikimedia.org/wiki/File:Chinese_Immigration_Act_of_1885_certificate_VPL_30625.jpg",
    "license": "No known copyright restrictions",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "connection": "Discriminatory immigration laws and the Chinese head tax",
    "inquiry": "Find the amount paid and the conditions on the certificate. What does this document reveal about unequal treatment, and what does it leave out about the person’s experience?",
    "url": "images/grade7/headtax.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "komagata",
    "title": "Passengers aboard the Komagata Maru",
    "theme": "Immigration & citizenship",
    "date": "July 1914",
    "kind": "Photograph",
    "credit": "Photographer credited as H.W.R. / Vancouver Public Library",
    "source": "https://commons.wikimedia.org/wiki/File:The_S.S._Komagata_Maru_with_passengers_on_decks,_July_1914.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Komagata Maru, immigration restrictions and discrimination",
    "inquiry": "What details make the passengers’ situation visible? What policies and passenger accounts would help explain the scene beyond the photograph?",
    "url": "images/grade7/komagata.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "vancouver-riot",
    "title": "Boarded-up Chinatown shops after the 1907 riots",
    "theme": "Immigration & citizenship",
    "date": "1907",
    "kind": "Photograph",
    "credit": "Philip Timms / Vancouver Public Library, VPL 940",
    "source": "https://commons.wikimedia.org/wiki/File:Chinatown_riot_VPL_940_(10463603965).jpg",
    "license": "No known copyright restrictions",
    "licenseUrl": "https://www.flickr.com/commons/usage/",
    "connection": "Anti-Asian riots: causes, consequences and evidence",
    "inquiry": "What visible evidence records the damage and its aftermath? How could accounts from affected residents deepen our understanding of the event?",
    "url": "images/grade7/vancouver-riot.jpg",
    "era": "Western Expansion"
  },
  {
    "id": "construction-battalion",
    "title": "No. 2 Construction Battalion in Nova Scotia",
    "theme": "Military & sovereignty",
    "date": "1916",
    "kind": "Photograph",
    "credit": "H. C. Dodge / Canadian historical military photograph",
    "source": "https://commons.wikimedia.org/wiki/File:No._2_Construction_Battalion.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Black Canadians’ contributions to the First World War",
    "inquiry": "What does the group photograph show about organization and service? What sources would reveal the discrimination these soldiers faced and the work they performed?",
    "url": "images/grade7/construction-battalion.jpg",
    "era": "WWI"
  },
  {
    "id": "vimy-soldiers",
    "title": "Canadian soldiers at Vimy Ridge",
    "theme": "Military & sovereignty",
    "date": "April 1917",
    "kind": "Photograph",
    "credit": "William Ivor Castle / Library and Archives Canada, PA-001101",
    "source": "https://commons.wikimedia.org/wiki/File:Vimy_Ridge_-_captured_machine_gun_fortification.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Canadian participation in the First World War",
    "inquiry": "What evidence shows the conditions in which soldiers worked? What can and cannot this single photograph support about the significance of the battle?",
    "url": "images/grade7/vimy-soldiers.jpg",
    "era": "WWI"
  },
  {
    "id": "vimy-map",
    "title": "Vimy Ridge: a barrage and objectives map",
    "theme": "Military & sovereignty",
    "date": "1917",
    "kind": "Military planning map",
    "credit": "1st Field Survey Company, Royal Engineers; Library and Archives Canada, NMC 111113",
    "source": "https://commons.wikimedia.org/wiki/File:Vimy_Ridge_1917-barrage_map.jpg",
    "license": "Public domain",
    "licenseUrl": "https://creativecommons.org/publicdomain/mark/1.0/",
    "connection": "Military accomplishments and the use of maps as evidence",
    "inquiry": "What do the lines, boundaries and labels show about planning? Compare the map with the soldiers’ photograph: what does each source contribute?",
    "url": "images/grade7/vimy-map.jpg",
    "era": "WWI"
  }
];
