'use strict';
const studyKey='bgsd-strata-notebook-v2';
let fieldRecord=Studio.read(studyKey,{found:[],notes:{},checks:{}});
if(!fieldRecord||!Array.isArray(fieldRecord.found)||typeof fieldRecord.notes!=='object'||!fieldRecord.notes||typeof fieldRecord.checks!=='object'||!fieldRecord.checks)fieldRecord={found:[],notes:{},checks:{}};
fieldRecord.found.slice(0,8).forEach((value,i)=>found[i]=value===true);
let studyMode='observe',clearIndex=0,clearingStage='over';
const evidence={
 DPP:{group:'Horned dinosaur',observation:'The skull has a bony horn and a frill.',inference:'The animal must have lived alone.',reason:'A horn and frill describe preserved structures. Social behaviour needs evidence from the wider bonebed.',age:76},
 DRY:{group:'Theropod',observation:'The bonebed contains several Albertosaurus individuals.',inference:'The dinosaurs definitely hunted in packs.',reason:'Several individuals together is evidence. It does not by itself prove how they hunted.',age:69},
 MAC:{group:'Armoured dinosaur',observation:'Researchers found fossil plant material in the stomach contents.',inference:'This animal always ate only one kind of plant.',reason:'Stomach contents provide evidence of a meal. They do not tell us every meal the animal ever ate.',age:110},
 PIP:{group:'Horned dinosaur',observation:'The skull has a thick bony nasal boss.',inference:'Every dinosaur with a bony boss used it for fighting.',reason:'The boss is a structure we can observe. Its possible uses are interpretations to investigate.',age:72.5},
 HSC:{group:'Duck-billed dinosaur',observation:'The preserved skull has a broad, beak-like front.',inference:'This animal ate exactly the same plants every day.',reason:'The skull shape is preserved evidence. A precise daily diet is not shown by the skull alone.',age:72},
 DEV:{group:'Duck-billed dinosaur',observation:'Eggshells and nests were found at this locality.',inference:'Every adult dinosaur at this site cared for young.',reason:'Eggshells and nests support an interpretation of nesting. Parental behaviour requires more evidence.',age:75},
 MAN:{group:'Armoured dinosaur',observation:'Reference skeletons preserve bony armour and a tail club.',inference:'This dinosaur won every fight it had.',reason:'Armour and a tail club are preserved structures. We cannot recover every encounter from them.',age:76},
 COR:{group:'Duck-billed dinosaur',observation:'The skull has a tall, hollow bony crest.',inference:'We know exactly what its calls sounded like.',reason:'The crest is evidence. Models can explore possible sounds, but do not let us hear the living animal.',age:76}
};
function saveField(){fieldRecord.found=[...found];const ok=Studio.save(studyKey,fieldRecord);const el=document.getElementById('study-save');if(el)el.textContent=ok?'Completed finds and notes saved on this browser.':'Browser storage is unavailable. Print or download your notebook to keep it.';}
function note(){const code=SITES[current].grid;return fieldRecord.notes[code]||(fieldRecord.notes[code]={observation:'',inference:'',question:''});}
function renderStudy(){
 const s=SITES[current],n=note(),e=evidence[s.grid],esc=Studio.esc;const host=document.getElementById('field-study');
 host.innerHTML=`<div class="study-head"><div><div class="eyebrow" style="letter-spacing:.12em">Investigate the evidence</div><h2 style="margin-top:9px">Your field notebook</h2></div><div><button class="study-button" id="study-export">Download notes</button> <button class="study-button" id="study-print">Print notebook</button></div></div><p class="study-note">${found[current]?esc(s.name)+' · '+esc(s.site):'Uncover the specimen to open this investigation. You can drag across the layers or use Clear next section.'}</p><div class="study-tabs" aria-label="Investigation mode"><button data-study="observe" aria-pressed="${studyMode==='observe'}">Observe &amp; infer</button><button data-study="evidence" aria-pressed="${studyMode==='evidence'}">Check the evidence</button><button data-study="compare" aria-pressed="${studyMode==='compare'}">Compare discoveries</button></div><div id="study-content"></div><p id="study-save" class="study-status" role="status"></p>`;
 const content=document.getElementById('study-content');
 if(studyMode==='compare')renderCompare(content);
 else if(!found[current])content.innerHTML='<p class="study-note">The current specimen is still covered. Complete the three clearing stages first.</p>';
 else if(studyMode==='observe')content.innerHTML=`<div class="study-layout"><div><label for="observation">I observe…</label><textarea id="observation" data-note="observation" placeholder="Describe a shape, texture or arrangement that you can see.">${esc(n.observation)}</textarea><label for="inference">I infer… because…</label><textarea id="inference" data-note="inference" placeholder="Make a claim and connect it to your evidence.">${esc(n.inference)}</textarea><label for="wonder">I still wonder…</label><textarea id="wonder" data-note="question" placeholder="What further evidence would help you?">${esc(n.question)}</textarea></div><div><h3>Observation → inference → question</h3><p class="study-note"><b>Observation:</b> ${esc(e.observation)}</p><p class="study-note"><b>Inference:</b> a possible explanation of what the evidence means. Use “may,” “could” or “suggests” when evidence is incomplete.</p><p class="study-note">Compare the excavation reconstruction with the life restoration. Which features do the images show? These are illustrations; use the evidence record for findings from real fossils.</p><div class="study-comparison"><strong>Evidence from real fossils</strong><p class="study-note">${esc(s.fact)}</p><p class="study-note">Rock formation: ${esc(s.formation)}<br>Approximate age: ${e.age} million years</p></div></div></div>`;
 else{
 const passed=fieldRecord.checks[s.grid]===true;content.innerHTML=`<h3>Which statement reports an observation?</h3><p class="study-quiz-note">Use the preserved structures and the field description. A confident-sounding claim still needs evidence.</p><div class="study-choices"><button data-evidence="inference" aria-pressed="false">${esc(e.inference)}</button><button data-evidence="observation" aria-pressed="${passed}">${esc(e.observation)}</button></div><div class="study-feedback" role="status" id="evidence-feedback">${passed?'Evidence check complete. '+esc(e.reason):''}</div>`;
 }
 host.querySelectorAll('[data-study]').forEach(b=>b.onclick=()=>{studyMode=b.dataset.study;renderStudy();});
 host.querySelectorAll('[data-note]').forEach(input=>input.oninput=()=>{note()[input.dataset.note]=input.value;saveField();});
 host.querySelectorAll('[data-evidence]').forEach(b=>b.onclick=()=>{const correct=b.dataset.evidence==='observation';if(correct)fieldRecord.checks[s.grid]=true;host.querySelectorAll('[data-evidence]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));document.getElementById('evidence-feedback').textContent=(correct?'That is an observation. ':'That is an interpretation, not a direct observation. ')+e.reason;saveField();});
 document.getElementById('study-export').onclick=exportNotebook;document.getElementById('study-print').onclick=()=>window.print();saveField();
}
function renderCompare(host){const available=SITES.filter((_,i)=>found[i]);if(available.length<2){host.innerHTML='<p class="study-note">Uncover at least two specimens to compare their evidence and ages.</p>';return;}
 host.innerHTML='<h3>Not all Alberta dinosaurs lived at the same time.</h3><div class="study-table"><table><thead><tr><th>Specimen</th><th>Group</th><th>Approx. age</th><th>Formation</th></tr></thead><tbody>'+[...available].sort((a,b)=>evidence[b.grid].age-evidence[a.grid].age).map(s=>`<tr><td>${s.name}</td><td>${evidence[s.grid].group}</td><td>${evidence[s.grid].age} million years</td><td>${s.formation}</td></tr>`).join('')+'</tbody></table></div><label for="compare-a">First specimen</label><select id="compare-a">'+available.map(s=>`<option value="${s.grid}">${s.name}</option>`).join('')+'</select><label for="compare-b">Second specimen</label><select id="compare-b">'+available.map((s,i)=>`<option value="${s.grid}" ${i===1?'selected':''}>${s.name}</option>`).join('')+'</select><div id="comparison" class="study-comparison" role="status"></div><p class="study-note">Age estimates describe the fossil context approximately. Similar ages do not prove two individuals met.</p>';
 const compare=()=>{const a=document.getElementById('compare-a').value,b=document.getElementById('compare-b').value;const d=Math.abs(evidence[a].age-evidence[b].age);document.getElementById('comparison').textContent=a===b?'Choose two different specimens.':`Their approximate ages differ by ${Number(d.toFixed(1))} million years. Compare their preserved features and the rock formations they came from.`;};document.getElementById('compare-a').onchange=compare;document.getElementById('compare-b').onchange=compare;compare();}
function exportNotebook(){const rows=[['Site','Specimen','Approximate age (million years)','Observation','Inference','Question','Evidence check']];SITES.forEach((s,i)=>{if(!found[i])return;const n=fieldRecord.notes[s.grid]||{};rows.push([s.site,s.name,evidence[s.grid].age,n.observation||'',n.inference||'',n.question||'',fieldRecord.checks[s.grid]?'Complete':'Not completed']);});Studio.download('strata-field-notebook.csv',Studio.csv(rows),'text/csv');}
// Wrap the existing game lifecycle so notebook state follows the selected specimen.
const loadFieldSite=loadSite;loadSite=function(i,redig=false){clearIndex=0;clearingStage='over';loadFieldSite(i,redig);renderStudy();document.getElementById('clearSection').disabled=revealed;};
const revealFieldSpecimen=reveal;reveal=function(){revealFieldSpecimen();saveField();renderStudy();document.getElementById('clearSection').disabled=true;};
document.getElementById('clearSection').onclick=()=>{if(revealed)return;if(stage!==clearingStage){clearIndex=0;clearingStage=stage;}clearNextSection(clearIndex++%12);};
renderCards();updateCount();loadSite(0);

