const assert=require('node:assert/strict');
const P=require('../progression.js'),E=require('../engine.js');
const road=E.starter('beam'),truss=E.starter('truss'),steel=truss.map(m=>m.type==='wood'?{...m,type:'steel'}:m);
const reinforced=truss.map(m=>m.type==='wood'&&(m.a.x===E.LEFT||m.b.x===E.RIGHT||(m.a.y===166&&m.b.y===166))?{...m,type:'steel'}:m);
const fresh=P.bootstrap(null,road);
assert.equal(fresh.challenge,'first');assert.equal(fresh.vehicle,'car');assert.deepEqual(fresh.members,road);assert.equal(fresh.progress.completed,0);
assert.deepEqual(P.levels.map(l=>l.vehicle),['car','truck','trailer','bus','semi','tanker','tank']);
assert(P.levels.every((l,i)=>!i||E.vehicles[l.vehicle].load>E.vehicles[P.levels[i-1].vehicle].load),'Each level must use a heavier vehicle');
const p=P.readProgress();
assert(P.isUnlocked('first',p)&&!P.isUnlocked('supply',p)&&!P.isUnlocked('tankTrial',p));
assert(P.isUnlocked('sandbox',p));
const attempt=(id,values={})=>P.recordWin(p,id,{pass:true,cost:1000,vehicle:P.challenges[id]?.vehicle,loadPercent:100,...values});
assert(!attempt('first',{pass:false}).earned,'A failed crossing must not unlock a level');
assert(!attempt('first',{cost:1101}).earned,'Over-budget crossings must not unlock a level');
assert(attempt('first',{cost:1100}).earned,'A crossing exactly at budget must count');
assert(!attempt('first',{vehicle:'truck'}).earned,'A different vehicle cannot earn the level');
assert(!attempt('first',{loadPercent:50}).earned,'A legacy lighter load cannot earn the level');
assert(!attempt('first',{cost:NaN}).earned&&!attempt('first',{cost:-1}).earned,'Invalid costs cannot earn progress');
assert(!attempt('heavy').earned&&!attempt('sandbox').earned,'Locked levels and Free build cannot unlock progress');
let progress=p;
for(const level of P.levels){
  const members=['car','truck'].includes(level.vehicle)?truss:['trailer','bus'].includes(level.vehicle)?reinforced:steel;
  const result=E.scan(members,level.vehicle);
  assert(result.pass&&result.cost<=level.budget,'Every level must be achievable with a student-built design within budget: '+level.vehicle);
  const win=P.recordWin(progress,level.id,{...result,vehicle:level.vehicle,loadPercent:100});
  assert(win.earned);assert.equal(win.progress.completed,P.levelIndex(level.id)+1);assert.equal(win.next,P.nextFor(level.id));progress=win.progress;
}
assert.equal(progress.completed,7);assert.equal(P.nextFor('tankTrial'),'sandbox');
const replay=P.recordWin(progress,'first',{pass:true,vehicle:'car',loadPercent:100,cost:961});
assert(replay.earned&&replay.progress.completed===7,'Replaying a completed level must not duplicate progress');
assert.equal(P.readProgress({version:1,completed:999}).completed,0);
assert.equal(P.readProgress({version:1,completed:1.5}).completed,0);
const old={members:steel,challenge:'tankTrial',vehicle:'tank',loadPercent:100,wind:12,trials:[{pass:true,mission:true}]};
const migrated=P.bootstrap(old,road);
assert.equal(migrated.vehicle,'car');assert.equal(migrated.challenge,'first');assert.deepEqual(migrated.members,road);
assert.deepEqual(migrated.freeBuildDraft.members,steel,'Earlier work must remain available in Free build');
assert.equal(migrated.progress.completed,0,'Previous preset-based trials must not unlock the new journey');
const session={...migrated,members:truss,challenge:'supply',vehicle:'truck',progress:{version:1,completed:1},campaignDraft:{members:truss},freeBuildDraft:{members:steel}};
const restored=P.bootstrap(JSON.parse(JSON.stringify(session)),road);
assert.equal(restored.challenge,'supply');assert.deepEqual(restored.members,truss);assert.equal(restored.progress.completed,1);
const file={format:'bridge-test-lab',version:4,campaignVersion:1,members:truss,vehicle:'car',challenge:'first',wind:0,loadPercent:100};
assert.equal(E.readDesign(file).campaignVersion,1);
assert.equal(E.readDesign({...file,version:3}).campaignVersion,undefined,'Old files must not gain journey provenance');
assert.throws(()=>E.readDesign({...file,campaignVersion:2}),/invalid challenge/);
console.log(JSON.stringify({levels:P.levels.length,allLevelsAchievable:true,migrationPreservesPreviousBridge:true,locksAndBudgets:true},null,2));
