const assert=require('node:assert/strict');
const P=require('../progression.js'),E=require('../engine.js');
const road=E.starter('beam'),truss=E.starter('truss'),steel=truss.map(m=>m.type==='wood'?{...m,type:'steel'}:m);
const reinforced=truss.map(m=>m.type==='wood'&&(m.a.x===E.LEFT||m.b.x===E.RIGHT||(m.a.y===166&&m.b.y===166))?{...m,type:'steel'}:m);
const fresh=P.bootstrap(null,road);
assert.equal(fresh.challenge,'first');assert.equal(fresh.vehicle,'car');assert.deepEqual(fresh.members,road);assert.equal(fresh.progress.completed,0);
assert.deepEqual(P.levels.slice(0,7).map(l=>l.vehicle),['car','truck','trailer','bus','semi','tanker','tank']);
assert(P.levels.slice(0,7).every((l,i)=>!i||E.vehicles[l.vehicle].load>E.vehicles[P.levels[i-1].vehicle].load),'The original vehicle levels stay in order');
assert.equal(P.levels.length,12);assert(P.levels.every(l=>l.hints.length===3));
const p=P.readProgress();
assert(P.isUnlocked('first',p)&&!P.isUnlocked('supply',p)&&!P.isUnlocked('tankTrial',p));
assert(P.isUnlocked('sandbox',p));
const attempt=(id,values={})=>P.recordWin(p,id,{pass:true,cost:1000,vehicle:P.challenges[id]?.vehicle,loadPercent:100,...values});
assert(!attempt('first',{pass:false}).earned,'A failed crossing must not unlock a level');
assert(!attempt('first',{cost:1101}).earned,'Over-budget crossings must not unlock a level');
assert(attempt('first',{cost:1100}).earned,'A crossing exactly at budget must count');
assert(!attempt('first',{vehicle:'truck'}).earned,'A different vehicle cannot earn the level');
assert(!attempt('first',{loadPercent:50}).earned,'A legacy lighter load cannot earn the level');
assert(!attempt('first',{cost:NaN}).earned&&!attempt('first',{cost:-1}).earned,'Invalid costs cannot earn progress');
assert(!attempt('heavy').earned&&!attempt('sandbox').earned,'Locked levels and Free build cannot unlock progress');
let progress=p;
for(const level of P.levels){
  const members=level.bridgeType?E.starter(level.bridgeType):['car','truck'].includes(level.vehicle)?truss:['trailer','bus'].includes(level.vehicle)?reinforced:steel;
  const result=E.scan(members,level.vehicle,level.wind||0),designOk=!level.bridgeType||E.matchesType(members,level.bridgeType);
  assert(result.pass&&result.cost<=level.budget,'Every level must be achievable with a student-built design within budget: '+level.vehicle);
  assert(designOk,'The achievable design must meet the structural goal: '+level.id);
  const run={...result,vehicle:level.vehicle,loadPercent:100,designOk,wind:level.wind||0};
  if(level.bridgeType)assert(!P.recordWin(progress,level.id,{...run,designOk:false}).earned,'A successful crossing with the wrong structure must not advance');
  if(level.wind!==undefined)assert(!P.recordWin(progress,level.id,{...run,wind:level.wind===0?28:0}).earned,'A different wind cannot earn a fixed-wind mission');
  const win=P.recordWin(progress,level.id,run);
  assert(win.earned);assert.equal(win.progress.completed,P.levelIndex(level.id)+1);assert.equal(win.next,P.nextFor(level.id));progress=win.progress;
}
assert.equal(progress.completed,12);assert.equal(P.nextFor('tankTrial'),'efficientTruss');assert.equal(P.nextFor('stormCrossing'),'sandbox');
const replay=P.recordWin(progress,'first',{pass:true,vehicle:'car',loadPercent:100,cost:961});
assert(replay.earned&&replay.progress.completed===12,'Replaying a completed level must not duplicate progress');
assert.equal(P.readProgress({version:1,completed:7}).completed,7,'The previous seven-level completion is preserved');
assert(P.isUnlocked('efficientTruss',{version:1,completed:7})&&!P.isUnlocked('steelBeam',{version:1,completed:7}),'Existing players can continue into the new missions');
const previousFinisher=P.bootstrap({members:steel,challenge:'sandbox',vehicle:'tank',wind:0,progress:{version:1,completed:7}},road);
assert.equal(previousFinisher.progress.completed,7);assert.deepEqual(previousFinisher.members,steel);
const storm=P.bootstrap({members:steel,challenge:'stormCrossing',vehicle:'tank',wind:0,progress:{version:1,completed:11}},road);
assert.equal(storm.wind,28,'The final mission restores its fixed gusty wind');
const decorativeLower=[...truss,{type:'steel',a:{x:E.LEFT+E.STEP,y:E.DECK+E.STEP},b:{x:E.LEFT+2*E.STEP,y:E.DECK+E.STEP}}];
assert(!E.matchesType(decorativeLower,'girder'),'One disconnected lower beam is not a beam frame');
const disconnectedArch=[...truss,{type:'steel',a:{x:E.LEFT+3*E.STEP,y:E.DECK-E.STEP},b:{x:E.LEFT+3*E.STEP,y:E.DECK-2*E.STEP}}];
assert(!E.matchesType(disconnectedArch,'arch'),'One raised piece is not a bank-to-bank steel arch');
assert(!E.matchesType(E.starter('suspension').filter(m=>m.type!=='cable'||m.a.x!==m.b.x),'suspension'),'Backstays alone cannot replace suspension hangers');
assert.equal(P.readProgress({version:1,completed:999}).completed,0);
assert.equal(P.readProgress({version:1,completed:1.5}).completed,0);
const old={members:steel,challenge:'tankTrial',vehicle:'tank',loadPercent:100,wind:12,trials:[{pass:true,mission:true}]};
const migrated=P.bootstrap(old,road);
assert.equal(migrated.vehicle,'car');assert.equal(migrated.challenge,'first');assert.deepEqual(migrated.members,road);
assert.deepEqual(migrated.freeBuildDraft.members,steel,'Earlier work must remain available in Free build');
assert.equal(migrated.progress.completed,0,'Previous preset-based trials must not unlock the new journey');
const session={...migrated,members:truss,challenge:'supply',vehicle:'truck',progress:{version:1,completed:1},campaignDraft:{members:truss},freeBuildDraft:{members:steel}};
const restored=P.bootstrap(JSON.parse(JSON.stringify(session)),road);
assert.equal(restored.challenge,'supply');assert.deepEqual(restored.members,truss);assert.equal(restored.progress.completed,1);
const file={format:'bridge-test-lab',version:4,campaignVersion:1,members:truss,vehicle:'car',challenge:'first',wind:0,loadPercent:100};
assert.equal(E.readDesign(file).campaignVersion,1);
assert.equal(E.readDesign({...file,version:3}).campaignVersion,undefined,'Old files must not gain journey provenance');
assert.throws(()=>E.readDesign({...file,campaignVersion:2}),/invalid challenge/);
console.log(JSON.stringify({levels:P.levels.length,allLevelsAchievable:true,migrationPreservesPreviousBridge:true,locksAndBudgets:true},null,2));
