'use strict';const W=PluralLab,$=id=>document.getElementById(id);let mode='build',words=[],index=0,independent=0,done=false,wrong=false,assisted=false,reviewWords=[],selected=null,sorted=new Map(),sortMisses=new Set();
function pool(){return W.words.filter(w=>$('filter').value==='all'||w.rule===$('filter').value);}
function start(custom=null){words=Studio.shuffle(custom||pool()).slice(0,10);index=0;independent=0;reviewWords=[];selected=null;sorted.clear();sortMisses.clear();$('review').hidden=true;if(mode==='build')renderWord();if(mode==='sort')renderSort();if(mode==='study')renderStudy();}
function renderWord(){done=false;wrong=false;assisted=false;$('round-title').textContent=`Word ${index+1} of ${words.length}`;$('score').textContent=`${independent} independent`;$('word').innerHTML=`<div class="word-hero">${words[index].singular}</div><p class="word-context">one ${words[index].singular} → two ______</p>`;$('answer').value='';$('answer').disabled=false;$('answer-form').hidden=false;$('check').disabled=false;$('hint').disabled=false;$('worked').disabled=false;$('feedback').textContent='';$('feedback').classList.remove('error');$('next').hidden=true;$('summary').hidden=true;}
function finish(correct){if(done)return;done=true;const w=words[index];if(correct&&!wrong&&!assisted)independent++;else reviewWords.push(w);$('score').textContent=`${independent} independent`;$('feedback').classList.remove('error');$('feedback').textContent=(correct?'Yes. ':'Let’s compare the two forms. ')+W.explain(w);$('answer').value=w.plural;$('answer').disabled=true;$('check').disabled=true;$('hint').disabled=true;$('worked').disabled=true;$('next').hidden=false;}
$('answer-form').onsubmit=e=>{e.preventDefault();if(done)return;const answer=$('answer').value;if(!W.normalize(answer)){$('feedback').textContent='Enter your plural word first.';return;}if(W.correct(words[index],answer))finish(true);else{wrong=true;$('feedback').classList.add('error');$('feedback').textContent=answer.includes("'")?'Try the plural without an apostrophe. An apostrophe can show possession.':'Look at the last letters of the singular word and try again. Show the pattern if you need support.';}};
$('hint').onclick=()=>{if(done)return;assisted=true;$('feedback').classList.remove('error');$('feedback').textContent=W.rules[words[index].rule].note;};$('worked').onclick=()=>{assisted=true;finish(false);};$('next').onclick=()=>{if(!done)return;index++;if(index<words.length){renderWord();Studio.focus('answer');}else{$('answer-form').hidden=true;$('word').innerHTML='';$('next').hidden=true;$('feedback').textContent='';$('round-title').textContent='Round complete';$('summary').hidden=false;$('summary').innerHTML=`<div class="round-summary"><h2>${independent} of ${words.length} built independently.</h2><p>${reviewWords.length?reviewWords.length+' words are ready for another look.':'You connected every word to its pattern.'}</p></div>`;$('review').hidden=!reviewWords.length;}};
function renderSort(){const rules=Object.keys(W.rules).filter(r=>words.some(w=>w.rule===r));$('sort-progress').textContent=`${sorted.size} / ${words.length} sorted`;$('sort-words').innerHTML=words.map((w,i)=>sorted.has(i)?'':`<button class="word-card" data-word="${i}" draggable="true" aria-pressed="${selected===i}">${w.singular} → ${w.plural}</button>`).join('');$('buckets').innerHTML=rules.map(r=>`<button class="bucket" data-bucket="${r}" aria-label="Sort selected word into ${W.rules[r].name}"><h3>${W.rules[r].name}</h3><span class="example">${W.rules[r].example}</span>${[...sorted.entries()].filter(([i,rule])=>rule===r).map(([i])=>`<span class="sorted">${words[i].singular} → ${words[i].plural}</span>`).join('')}</button>`).join('');if(sorted.size===words.length)$('sort-feedback').textContent=`All ${words.length} sorted. ${words.length-sortMisses.size} placed independently on the first try. Start a fresh round or study the patterns.`;
 $('sort-words').querySelectorAll('[data-word]').forEach(b=>{b.onclick=()=>{selected=Number(b.dataset.word);renderSort();$('sort-feedback').textContent=`Selected ${words[selected].singular} → ${words[selected].plural}. Choose a pattern.`;};b.ondragstart=e=>{selected=Number(b.dataset.word);e.dataTransfer.setData('text/plain',b.dataset.word);};});$('buckets').querySelectorAll('[data-bucket]').forEach(b=>{b.onclick=()=>place(b.dataset.bucket);b.ondragover=e=>e.preventDefault();b.ondrop=e=>{e.preventDefault();const value=e.dataTransfer.getData('text/plain');if(!/^\d+$/.test(value))return;const i=Number(value);if(i<0||i>=words.length||sorted.has(i))return;selected=i;place(b.dataset.bucket);};});}
function place(rule){if(selected===null||sorted.has(selected)){$('sort-feedback').textContent='Select a word card first.';return;}const w=words[selected];if(w.rule===rule){sorted.set(selected,rule);$('sort-feedback').textContent='That pattern fits. '+W.explain(w);selected=null;renderSort();}else{sortMisses.add(selected);$('sort-feedback').textContent='Compare the letters that changed. '+W.explain(w);}}
function renderStudy(){const rules=Object.keys(W.rules).filter(r=>$('filter').value==='all'||$('filter').value===r);$('pattern-study').innerHTML=rules.map(r=>`<div class="pattern-card"><h3>${W.rules[r].name}</h3><p class="example">${W.rules[r].example}</p><p class="small">${W.rules[r].note}</p></div>`).join('');$('study-table').innerHTML='<table><thead><tr><th>Singular</th><th>Plural</th><th>Pattern</th></tr></thead><tbody>'+pool().map(w=>`<tr><td>${w.singular}</td><td>${w.plural}</td><td>${W.rules[w.rule].name}</td></tr>`).join('')+'</tbody></table>';}
$('filter').innerHTML+=Object.entries(W.rules).map(([r,v])=>`<option value="${r}">${v.name}</option>`).join('');$('filter').onchange=()=>start();$('fresh').onclick=()=>start();$('review').onclick=()=>{const repeat=[...reviewWords];start(repeat);};
document.querySelector('.tabs').onclick=e=>{const b=e.target.closest('[data-mode]');if(!b||b.dataset.mode===mode)return;mode=b.dataset.mode;for(const m of ['build','sort','study'])$(m+'-view').hidden=m!==mode;document.querySelectorAll('[data-mode]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.mode===mode)));start();};$('print').onclick=()=>window.print();start();
