
(()=>{const $=id=>document.getElementById(id),D=READING_DATA,W=Workshop;let selected=new Set(),hinted=new Set();const key=D.passage.flat().filter(c=>c.isKey);
function render(){selected.clear();hinted.clear();$('passage').replaceChildren();D.passage.forEach((p,pi)=>{let para=document.createElement('p');p.forEach((c,ci)=>{if(c.isClickable){let b=document.createElement('button');b.type='button';b.textContent=c.text;b.dataset.key=String(!!c.isKey);b.dataset.id=pi+'-'+ci;b.setAttribute('aria-pressed','false');b.onclick=()=>{let id=b.dataset.id;if(selected.has(id)){selected.delete(id);b.setAttribute('aria-pressed','false')}else if(c.isKey){selected.add(id);b.setAttribute('aria-pressed','true')}$('meaning').textContent=D.definitions[c.text]||'This detail adds description. Look for an idea that explains the topic or an important vocabulary term.';status()};para.append(b)}else para.append(document.createTextNode(c.text))});$('passage').append(para)});$('quiz-panel').hidden=true;$('meaning').textContent='Choose an underlined word or phrase in the passage.';$('explain').value='';$('quiz-status').textContent='';status();renderQuiz()}
function status(){$('find-status').textContent=`${selected.size} of ${key.length} ${D.goal} found${selected.size===key.length?'. Ready to explain and check your understanding.':'. Select underlined ideas and investigate their meanings.'}`}
function renderQuiz(){$('quiz').replaceChildren();D.quiz.forEach((q,i)=>{let f=document.createElement('fieldset');f.className='quiz-item';f.dataset.id=q.id;let l=document.createElement('legend');l.textContent=(i+1)+'. '+q.question;f.append(l);W.shuffle(q.options).forEach(o=>{let label=document.createElement('label'),r=document.createElement('input');r.type='radio';r.name='q-'+q.id;r.value=o;label.append(r,document.createTextNode(o));f.append(label)});$('quiz').append(f)})}
$('hint').onclick=()=>{const b=[...$('passage').querySelectorAll('button')].find(x=>x.dataset.key==='true'&&!selected.has(x.dataset.id));if(b){hinted.add(b.dataset.id);$('meaning').textContent='Look closely at: '+b.textContent+'. '+(D.definitions[b.textContent]||'');b.focus()}else $('meaning').textContent='You found all the key ideas. Explain one in your own words.'};
$('quiz-open').onclick=()=>{$('quiz-panel').hidden=false;$('quiz-panel').scrollIntoView?.({behavior:'smooth',block:'start'})};
$('check').onclick=()=>{let score=0,answered=0;D.quiz.forEach(q=>{let f=$('quiz').querySelector('[data-id="'+q.id+'"]');f.querySelector('.answer-note')?.remove();let choice=f.querySelector('input:checked'),note=document.createElement('div');note.className='answer-note';if(!choice){note.textContent='Choose an answer, then check again.';note.classList.add('wrong')}else{answered++;let ok=choice.value===q.answer;if(ok)score++;else note.classList.add('wrong');note.textContent=(ok?'Correct. ':'Try again. ')+q.explanation+' Find evidence in the passage.'}f.append(note)});$('quiz-status').textContent=`${score} of ${D.quiz.length} correct; ${answered} answered. You can revise your answers and check again.`};
$('read').onclick=()=>{if(!W.speak(D.passage.map(p=>p.map(c=>c.text).join('')).join('\n\n')))$('find-status').textContent='Reading aloud is unavailable in this browser. The full passage is shown above.'};$('stop').onclick=()=>window.speechSynthesis?.cancel();$('restart').onclick=()=>{window.speechSynthesis?.cancel();render()};$('print').onclick=()=>{$('quiz-panel').hidden=false;window.print()};$('download').onclick=()=>{let text=D.title+'\n\nMy explanation: '+$('explain').value+'\n\n';D.quiz.forEach(q=>{let r=$('quiz').querySelector('input[name="q-'+q.id+'"]:checked');text+=q.question+'\nMy answer: '+(r?.value||'Not answered')+'\n\n'});W.download('reading-work.txt',text)};render();
})();