'use strict';
const N=NumberLab,$=id=>document.getElementById(id),key='bgsd-number-studio-v2';
const stored=Studio.read(key,null);let record={progress:N.fresh(),history:[],session:null};
if(stored&&stored.version===2&&N.skills.every(s=>stored.progress?.[s]&&Number.isInteger(stored.progress[s].level)&&stored.progress[s].level>=0&&stored.progress[s].level<=4&&Array.isArray(stored.progress[s].window))&&Array.isArray(stored.history))record=stored;
let skill='bonds',view='practice',round=0,answered=false,wrong=false,assisted=false,adjustment='',q,lab=[0,0,3,5,2];
function persist(){record.version=2;if(!Studio.save(key,record))$('storage-status').textContent='Browser storage is unavailable; use Download CSV to keep your record.';}
function model(p){
 if(p[0]||p[1])return '<div class="counters" aria-label="Place-value counters">'+p.map((c,i)=>c?`<div class="counter-group"><b>${N.places[i]}</b>${Array.from({length:Math.min(c,30)},()=>`<span class="counter">${N.values[i].toLocaleString()}</span>`).join('')}</div>`:'').join('')+'</div>';
 return `<div class="blocks" role="img" aria-label="${p[2]} hundreds, ${p[3]} tens and ${p[4]} ones"><div class="block-group">${'<span class="hundred"></span>'.repeat(p[2])}</div><div class="block-group">${'<span class="ten"></span>'.repeat(p[3])}</div><div class="ones">${'<span class="one"></span>'.repeat(p[4])}</div></div><p class="small muted">Blue flat = 100 · gold rod = 10 · green square = 1</p>`;
}
function rememberSession(){record.session={skill,round,answered,wrong,assisted,adjustment,q,adaptive:$('adaptive').checked};persist();}
function updateTabs(){$('skill-tabs').innerHTML=N.skills.map(s=>`<button class="btn" data-skill="${s}" aria-pressed="${s===skill}">${N.names[s]}<span>${N.levels[record.progress[s].level]}</span></button>`).join('');}
function newQuestion(){answered=false;wrong=false;assisted=false;adjustment='';q=N.makeQuestion(skill,record.progress[skill].level,Math.floor(Math.random()*0x7fffffff));rememberSession();renderQuestion();}
function renderQuestion(){
 updateTabs();$('skill-title').textContent=N.names[skill];$('level-tag').textContent=N.levels[q.level];$('question-count').textContent=`Question ${round+1} of 10`;
 $('session-bar').style.width=round*10+'%';$('session-status').textContent=`${round} questions completed in this round.`;
 let h=`<h3 style="margin-top:22px">${q.prompt}</h3>`;
 if(skill==='bonds'||skill==='trade'&&q.level===0)h+=`<div class="equation"><span>${q.n.toLocaleString()}</span><span>=</span><span>${q.first.toLocaleString()}</span><span>+</span><label class="sr-only" for="answer">Missing part</label><input id="answer" type="number" min="0" step="1" inputmode="numeric"></div>`;
 else if(skill==='build'){const from=q.level===4?0:q.level===3?2:q.level>0?3:4;h+=`<p class="big-number">${q.n.toLocaleString()}</p><div class="place-chart" style="--places:${5-from}">`+N.places.map((name,i)=>i<from?`<input id="place-${i}" type="hidden" value="0">`:`<div class="place"><label for="place-${i}">${name}</label><input id="place-${i}" type="number" min="0" max="9" step="1" inputmode="numeric" placeholder="0"></div>`).join('')+'</div><p class="small muted">Use one digit in every place, including zero.</p>';}
 else h+=model(q.parts)+`<label for="answer">Total value</label><input id="answer" type="number" min="0" step="1" inputmode="numeric">`;
 $('question').innerHTML=h+'<div id="support" hidden></div>';$('feedback').textContent='';$('feedback').classList.remove('error');$('check').hidden=answered;$('hint').hidden=answered;$('reveal').hidden=answered;$('next').hidden=!answered;
 if(answered){$('feedback').textContent=N.explanation(q)+' '+adjustment;$('question').querySelectorAll('input').forEach(e=>e.disabled=true);}
 else if(assisted)showModel(false);
 $('start-level').value=record.progress[skill].level;
}
function showModel(mark=true){if(mark){assisted=true;rememberSession();}const support=$('support');support.hidden=false;support.innerHTML=skill==='bonds'||skill==='trade'&&q.level===0?`<div class="rule-card" style="margin-top:20px"><strong>Whole − known part = missing part.</strong><p>Start at ${q.first.toLocaleString()}. How much more gets you to ${q.n.toLocaleString()}?</p><p>${q.n.toLocaleString()} − ${q.first.toLocaleString()} = ?</p></div>`:model(N.parts(q.n))+`<p class="small">Read each place separately. A zero holds an empty place.</p>`;}
function finish(correct){if(answered)return;answered=true;const clean=correct&&!wrong&&!assisted;adjustment=N.adapt(record.progress,skill,clean,assisted||wrong,$('adaptive').checked);record.history.push({skill,level:q.level,number:q.n,firstTry:clean,supported:assisted||wrong,date:new Date().toISOString().slice(0,10)});record.history=record.history.slice(-100);rememberSession();$('feedback').classList.remove('error');$('feedback').textContent=(correct?'Yes. ':'Let’s connect the model to the number. ')+N.explanation(q)+' '+adjustment;$('question').querySelectorAll('input').forEach(e=>e.disabled=true);$('check').hidden=true;$('hint').hidden=true;$('reveal').hidden=true;$('next').hidden=false;updateTabs();}
function checkAnswer(){if(answered)return;const input=skill==='build'?N.values.map((_,i)=>$('place-'+i).value):$('answer').value;const result=N.check(q,input);if(result===null){$('feedback').classList.add('error');$('feedback').textContent=skill==='build'?'Enter one whole-number digit (0–9) in every place.':'Enter a whole number, including zero when needed.';return;}if(result)finish(true);else{wrong=true;assisted=true;rememberSession();showModel(false);$('feedback').classList.add('error');$('feedback').textContent=skill==='build'?'Check the value of each digit. You can keep working on this same number.':'Try once more. Check each group’s value rather than just counting the groups.';}}
function startRound(){record.progress[skill].level=Number($('start-level').value);record.progress[skill].window=[];round=0;newQuestion();}
function setView(name){view=name;for(const v of ['practice','lab','progress'])$(v+'-view').hidden=v!==name;document.querySelectorAll('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===name)));if(name==='lab')renderLab();if(name==='progress')renderProgress();}
function renderLab(){$('lab-controls').innerHTML=N.places.map((p,i)=>`<div class="place"><h3>${p}</h3><div class="lab-count">${lab[i]}</div><div class="lab-adjust"><button class="btn small" data-adjust="${i},-1" aria-label="Remove one ${p.toLowerCase()} counter" ${lab[i]===0?'disabled':''}>−</button> <button class="btn small" data-adjust="${i},1" aria-label="Add one ${p.toLowerCase()} counter" ${lab[i]===30?'disabled':''}>+</button></div></div>`).join('');$('lab-total').textContent=N.total(lab).toLocaleString();$('lab-model').innerHTML=model(lab);$('trade-controls').innerHTML=[4,3,2,1].map(i=>`<div><button class="btn small" data-trade="${i},up" ${lab[i]<10||lab[i-1]>=30?'disabled':''}>10 ${N.places[i].toLowerCase()} → 1 ${N.places[i-1].toLowerCase().replace(/s$/,'')}</button><button class="btn small" style="margin-top:5px" data-trade="${i},down" ${lab[i-1]<1||lab[i]>20?'disabled':''}>Trade back</button></div>`).join('');}
function renderProgress(){$('progress-table').innerHTML='<table><thead><tr><th>Skill</th><th>Current range</th><th>Questions</th><th>Independent</th><th>Supported</th></tr></thead><tbody>'+N.skills.map(s=>{const p=record.progress[s];return `<tr><td>${N.names[s]}</td><td>${N.levels[p.level]}</td><td>${p.attempted}</td><td>${p.firstTry}</td><td>${p.supported}</td></tr>`;}).join('')+'</tbody></table>';$('history').innerHTML=record.history.length?'<table><thead><tr><th>Skill</th><th>Number</th><th>Range</th><th>How it went</th></tr></thead><tbody>'+record.history.slice(-15).reverse().map(r=>`<tr><td>${N.names[r.skill]}</td><td>${r.number.toLocaleString()}</td><td>${N.levels[r.level]}</td><td>${r.firstTry?'Independent':'With support'}</td></tr>`).join('')+'</tbody></table>':'<p>Complete a question to begin your record.</p>';}
$('start-level').innerHTML=N.levels.map((l,i)=>`<option value="${i}">${l}</option>`).join('');
document.querySelector('.tabs').addEventListener('click',e=>{if(e.target.closest('[data-view]'))setView(e.target.closest('[data-view]').dataset.view);});
$('skill-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-skill]');if(!b||b.dataset.skill===skill)return;skill=b.dataset.skill;round=0;newQuestion();});
$('check').onclick=checkAnswer;$('hint').onclick=()=>showModel();$('reveal').onclick=()=>{assisted=true;finish(false);};$('start').onclick=startRound;
$('question').addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();checkAnswer();}});
$('next').onclick=()=>{round++;if(round>=10){$('question-count').textContent='Round complete';$('question').innerHTML=`<div class="summary-banner" style="margin-top:22px"><h2>Ten questions. More connections.</h2><p>You practised ${N.names[skill].toLowerCase()}.</p><p>Your current range: <strong>${N.levels[record.progress[skill].level]}</strong>.</p><button class="btn primary" id="again">Start another round</button></div>`;$('feedback').textContent='Open Progress to see your independent and supported practice.';$('next').hidden=true;record.session=null;persist();$('again').onclick=()=>{round=0;newQuestion();};}else{newQuestion();Studio.focus(skill==='build'?'place-'+(q.level===4?0:q.level===3?2:q.level>0?3:4):'answer');}};
$('lab-load').onclick=()=>{const n=N.validNumber($('lab-number').value);if(n===null||n>99999){$('lab-feedback').textContent='Use a whole number from 0 to 99,999.';return;}lab=N.parts(n);$('lab-feedback').textContent='Now trade a group of ten. Watch the total stay the same.';renderLab();};
$('lab-controls').onclick=e=>{const b=e.target.closest('[data-adjust]');if(!b)return;const[i,d]=b.dataset.adjust.split(',').map(Number);lab[i]=Math.min(30,Math.max(0,lab[i]+d));$('lab-feedback').textContent='Adding or removing a counter changes the value.';renderLab();};
$('trade-controls').onclick=e=>{const b=e.target.closest('[data-trade]');if(!b||b.disabled)return;const[t,d]=b.dataset.trade.split(',');const i=Number(t),before=N.total(lab);if(d==='up'){lab[i]-=10;lab[i-1]++;}else{lab[i-1]--;lab[i]+=10;}$('lab-feedback').textContent=`Same value: ${before.toLocaleString()} = ${N.total(lab).toLocaleString()}. Only the grouping changed.`;renderLab();};
$('export').onclick=()=>Studio.download('number-practice.csv',Studio.csv([['Date','Skill','Range','Number','Independent','Supported'],...record.history.map(r=>[r.date,N.names[r.skill],N.levels[r.level],r.number,r.firstTry,r.supported])]),'text/csv');$('print').onclick=()=>window.print();
$('reset').onclick=()=>{if(!confirm('Clear the number practice record saved on this browser?'))return;record={progress:N.fresh(),history:[],session:null};round=0;newQuestion();renderProgress();$('save-notice').textContent='This browser’s practice record was cleared.';};
const saved=record.session;if(saved&&N.skills.includes(saved.skill)&&saved.q?.skill===saved.skill&&Number.isInteger(saved.q.level)&&saved.q.level>=0&&saved.q.level<=4&&Array.isArray(saved.q.parts)&&saved.round>=0&&saved.round<10){({skill,round,answered,wrong,assisted,adjustment,q}=saved);$('adaptive').checked=saved.adaptive!==false;renderQuestion();}else newQuestion();
