/* Fictional classroom scenarios. Primary-source excerpts are attributed below. */
window.ROOTS_DATA = {
  values: [
    {id:'rights', name:'Individual rights & freedoms', lane:'individual', text:'Protect a person’s freedom to express ideas and make choices, with respect for the rights of others.', example:'A resident can publicly criticize a town policy.'},
    {id:'property', name:'Private property', lane:'individual', text:'People can own property and make decisions about its use.', example:'A person decides whether to lend their own camera.'},
    {id:'self', name:'Self-interest', lane:'individual', text:'People pursue goals and opportunities that matter to them.', example:'A student chooses a course because it supports their own career goal.'},
    {id:'competition', name:'Competition', lane:'individual', text:'People or businesses compete for customers, opportunities or rewards.', example:'Two shops try to attract customers with better prices and service.'},
    {id:'freedom', name:'Economic freedom', lane:'individual', text:'People make economic choices, such as where to work and what to buy or sell, within the law.', example:'A mechanic chooses to start an independent bicycle-repair business.'},
    {id:'reliance', name:'Self-reliance', lane:'individual', text:'People develop skills and take responsibility for meeting their own needs.', example:'A person learns how to repair their own bicycle.'},
    {id:'interest', name:'Collective interest', lane:'shared', text:'Consider the well-being of the community as a whole.', example:'A town plans a park that residents across the community can enjoy.'},
    {id:'cooperation', name:'Cooperation', lane:'shared', text:'People work together toward a shared goal.', example:'Neighbours pool their effort to maintain a community garden.'},
    {id:'responsibility', name:'Collective responsibility', lane:'shared', text:'People share responsibility for supporting one another and addressing common problems.', example:'Residents contribute to a shared flood-recovery effort.'},
    {id:'equality', name:'Economic equality', lane:'shared', text:'Seek less unequal access to resources and the means to meet basic needs.', example:'A fund helps students who cannot afford necessary school supplies.'},
    {id:'public', name:'Public property', lane:'shared', text:'Resources or services are owned by a public authority on behalf of the community.', example:'A municipality owns and maintains a public park.'},
    {id:'norms', name:'Collective norms', lane:'shared', text:'Shared expectations guide how members of a group act.', example:'A team follows a shared agreement about respectful discussion.'}
  ],
  cases: [
    {id:'garden', title:'The empty lot', image:'community', tag:'Neighbourhood', question:'Who should decide how this space is used?', context:'The town owns an empty lot. Residents want to grow food, but tools, water and space are limited. Choose a plan for a one-year trial.', evidence:['The land belongs to the town.','Garden space and water are limited.','Residents want to grow food.'], options:[
      {title:'Give residents their own plots',text:'Residents lease small plots and decide what to grow. Each gardener buys supplies and keeps their harvest.',lane:'individual',values:['reliance','freedom'],benefit:'Gardeners have control over their choices and a direct reward for their work.',tradeoff:'People with less money, time or gardening experience may have fewer opportunities.',question:'How could someone without tools take part?'},
      {title:'Grow one shared garden',text:'Volunteers plan, plant and harvest together. Produce is shared through a community food program.',lane:'shared',values:['cooperation','interest'],benefit:'People can combine skills and resources to address a shared need.',tradeoff:'Volunteers must agree on decisions and how the harvest will be distributed.',question:'How would the group recognize different amounts of effort?'},
      {title:'Make room for both',text:'Offer individual plots alongside a shared bed. Gardeners contribute to a common tool collection.',lane:'both',values:['reliance','cooperation'],benefit:'Residents have some personal control while sharing useful resources.',tradeoff:'Someone must manage access to tools and divide the limited space fairly.',question:'What would make the split fair to different residents?'}
    ]},
    {id:'lunch',title:'Lunch for everyone?',image:'school',tag:'School',question:'How should a school make lunch available?',context:'Some students bring food, some buy it, and others struggle to afford lunch. The school can start a program, but its budget is limited.',evidence:['Some students struggle to afford lunch.','The school has a limited budget.','Students have different food preferences.'],options:[
      {title:'Let each family choose',text:'Families arrange lunches or buy from independent vendors. Vendors decide their menus and prices.',lane:'individual',values:['freedom','competition'],benefit:'Families have choice, and vendors can compete on menu and service.',tradeoff:'Students with less money may still have difficulty getting a meal.',question:'How could access be improved while keeping choice?'},
      {title:'Fund a basic meal for every student',text:'The school seeks shared funding and provides a basic lunch to everyone who wants it.',lane:'shared',values:['equality','responsibility'],benefit:'A common program can make lunch available regardless of family income.',tradeoff:'The community must fund the program; menu choices may be limited.',question:'What funding plan would be sustainable?'},
      {title:'Combine a basic meal with extra choices',text:'Offer a funded basic lunch and allow students to buy alternatives from vendors.',lane:'both',values:['equality','freedom'],benefit:'A basic meal is available while families retain additional choices.',tradeoff:'Different options could create visible differences between students.',question:'How could the school offer choices without creating stigma?'}
    ]},
    {id:'transit',title:'Getting around town',image:'community',tag:'Transport',question:'Who should provide the bus service?',context:'A growing town needs transportation. Busy routes could earn money, but a quiet neighbourhood also needs a reliable way to reach school, work and shops.',evidence:['Busy routes could earn money.','A quiet neighbourhood needs reliable transport.','Residents need to reach school, work and shops.'],options:[
      {title:'Invite private bus companies',text:'Companies choose routes and fares within town rules. Passengers choose which service to use.',lane:'individual',values:['competition','freedom'],benefit:'Providers can compete and respond to customer demand.',tradeoff:'A route with fewer paying customers may receive less service.',question:'What would happen to residents on less profitable routes?'},
      {title:'Run a publicly owned bus service',text:'The town owns the buses and shares costs through fares and public funding. Routes consider community access.',lane:'shared',values:['public','interest'],benefit:'The town can prioritize access even where a route earns less money.',tradeoff:'Residents must share costs and debate which routes get limited funding.',question:'How should the town decide where to put a new route?'},
      {title:'Build a public network with extra services',text:'The town runs core routes. Private providers can offer additional trips or routes.',lane:'both',values:['public','competition'],benefit:'A common network can coexist with extra options.',tradeoff:'Tickets, schedules and responsibility need coordination.',question:'Who should make sure the services work together?'}
    ]},
    {id:'market',title:'Market day',image:'market',tag:'Local business',question:'How should the vendors organize?',context:'A group of local vendors can rent market space. They want enough income to stay open and hope residents can afford good food.',evidence:['Vendors need enough income to stay open.','Vendors share a market location.','Residents have different food budgets.'],options:[
      {title:'Compete as independent stalls',text:'Each vendor sets prices, chooses products and keeps their own earnings.',lane:'individual',values:['competition','self'],benefit:'Vendors can pursue their own goals and try different approaches.',tradeoff:'Price competition may help some customers while squeezing smaller vendors.',question:'How might a small new vendor compete?'},
      {title:'Create a vendor cooperative',text:'Vendors agree on shared decisions, pool some costs and distribute returns using agreed rules.',lane:'shared',values:['cooperation','interest'],benefit:'Members can share resources and negotiate together.',tradeoff:'Members need agreement about prices, work and how returns are shared.',question:'How should the cooperative handle disagreement?'},
      {title:'Stay independent and share a food program',text:'Vendors keep their businesses and contribute to a jointly managed affordable-food box.',lane:'both',values:['freedom','responsibility'],benefit:'Independent enterprise can support a common community goal.',tradeoff:'Contributions affect vendors’ costs and require a reliable agreement.',question:'What contribution rule could members sustain?'}
    ]},
    {id:'tools',title:'The makerspace budget',image:'school',tag:'Creative work',question:'How should students get the tools they need?',context:'A student makerspace can buy only a few new tools. Some students already own equipment; others do not. Everyone wants to make a project.',evidence:['The makerspace can buy only a few tools.','Some students already own equipment.','Everyone wants to make a project.'],options:[
      {title:'Have students supply their own tools',text:'Students choose what to buy or borrow and decide how to use their personal equipment.',lane:'individual',values:['property','reliance'],benefit:'Students have control over equipment chosen for their own projects.',tradeoff:'Different family resources may affect which projects are possible.',question:'What could support someone who has no equipment?'},
      {title:'Build a shared tool library',text:'Pool the budget for tools everyone can book. Create common care and booking rules.',lane:'shared',values:['cooperation','equality'],benefit:'Sharing tools can give more students access to equipment.',tradeoff:'Popular tools may have waiting lists and need collective care.',question:'What booking rule would respect different needs?'},
      {title:'Share essentials; allow personal extras',text:'Provide a common set of tools and let students use their own additional equipment.',lane:'both',values:['equality','property'],benefit:'A common starting point leaves space for personal choices.',tradeoff:'The group must decide what counts as an essential tool.',question:'Which tools should be available to every student?'}
    ]},
    {id:'project',title:'One team, different contributions',image:'school',tag:'Group project',question:'How should a team’s work be recognized?',context:'Four students make a project together. Their contributions differ, and some work is easier to see than other work. The teacher wants both effort and cooperation to matter.',evidence:['Four students work on one project.','Some contributions are less visible.','The teacher wants effort and cooperation to matter.'],options:[
      {title:'Recognize each person’s contribution',text:'Students document their own work and receive separate recognition for it.',lane:'individual',values:['reliance','self'],benefit:'Individual effort and initiative can be recognized directly.',tradeoff:'Members may focus on visible personal tasks rather than helping the team.',question:'How could hidden work be recognized?'},
      {title:'Recognize the shared result',text:'The group receives the same recognition for the project they created together.',lane:'shared',values:['cooperation','responsibility'],benefit:'Members have a reason to help one another succeed.',tradeoff:'Some students may feel unequal effort is not acknowledged.',question:'How could the group address unequal participation?'},
      {title:'Recognize both contributions and teamwork',text:'Combine a shared assessment of the project with individual reflections on contributions.',lane:'both',values:['reliance','cooperation'],benefit:'The process can acknowledge personal effort and a common result.',tradeoff:'Deciding how much weight each part receives can be difficult.',question:'What evidence would make the assessment fair?'}
    ]}
  ],
  sort: [
    {id:'price',text:'Two independent shops try to win customers through lower prices and better service.',image:'market',lane:'individual',value:'Competition',why:'The central action is competing for customers. Competition is a principle associated with individualism.'},
    {id:'park',text:'The municipality owns a park and maintains it for residents to use.',image:'community',lane:'shared',value:'Public property',why:'The municipality owns the resource on behalf of the community. That is public property.'},
    {id:'garden',text:'Neighbours pool their time and tools to grow food for a community program.',image:'community',lane:'shared',value:'Cooperation',why:'Working together toward a shared goal emphasizes cooperation and collective interest.'},
    {id:'bike',text:'A person learns to repair their own bicycle so they can handle future problems themselves.',image:'market',lane:'individual',value:'Self-reliance',why:'Developing the ability to meet one’s own needs emphasizes self-reliance.'},
    {id:'speech',text:'A resident has the freedom to speak publicly against a town policy.',image:'community',lane:'individual',value:'Individual rights & freedoms',why:'The example centres on an individual’s freedom of expression. People can also use that freedom to benefit a community.'},
    {id:'supplies',text:'A shared fund pays for supplies for students who cannot afford them.',image:'school',lane:'shared',value:'Economic equality',why:'Pooling resources to reduce unequal access emphasizes economic equality and collective responsibility.'},
    {id:'flood',text:'Residents contribute to a shared effort to help neighbours recover from a flood.',image:'community',lane:'shared',value:'Collective responsibility',why:'The community takes shared responsibility for supporting people facing a common problem.'},
    {id:'camera',text:'A person owns a camera and decides whether someone else may borrow it.',image:'school',lane:'individual',value:'Private property',why:'The owner controls the use of their own possession. This emphasizes private property.'},
    {id:'goal',text:'A student chooses a course because it supports their own career goal.',image:'school',lane:'individual',value:'Self-interest',why:'The decision prioritizes a personal goal. Self-interest can coexist with concern for others.'},
    {id:'agreement',text:'A team follows a shared agreement about how members take turns in discussions.',image:'school',lane:'shared',value:'Collective norms',why:'A shared expectation guides group behaviour. Collective norms help a group work together.'},
    {id:'library',text:'A publicly funded library lets each reader choose which books to borrow.',image:'community',lane:'both',value:'Public provision + individual choice',why:'A shared service supports individual choices. This example deliberately combines the two lenses.'},
    {id:'cleanup',text:'Independent market vendors run their own businesses and work together to clean the shared square.',image:'market',lane:'both',value:'Economic freedom + cooperation',why:'Independent enterprise and cooperative action appear together. One does not cancel the other.'}
  ],
  sources: [
    {id:'locke',name:'John Locke',date:'1690',title:'Second Treatise of Government',location:'Chapter II, section 6',quote:'no one ought to harm another in his life, health, liberty, or possessions',explain:'Locke argues for protecting people’s lives, liberties and possessions. His account also places duties on people to respect one another.',question:'Which individual right is protected here? What responsibility comes with it?',url:'https://www.gutenberg.org/files/7370/7370-h/7370-h.htm'},
    {id:'rousseau',name:'Jean-Jacques Rousseau',date:'1762',title:'The Social Contract',location:'Book I, chapter VI · G. D. H. Cole translation',quote:'Each of us puts his person and all his power in common under the supreme direction of the general will',explain:'Rousseau describes people forming a political community around a general will directed toward common interests. Interpreting that will and protecting dissent raise important questions.',question:'What could joining a shared political community make possible? What might a dissenter question?',url:'https://www.gutenberg.org/cache/epub/46333/pg46333-images.html'},
    {id:'mill',name:'John Stuart Mill',date:'1859',title:'On Liberty',location:'Chapter I',quote:'Over himself, over his own body and mind, the individual is sovereign.',explain:'Mill defends personal liberty. His harm principle also allows limits on actions that harm others; the short excerpt must be read in that wider context.',question:'How could a community protect personal choice while addressing harm to others?',url:'https://www.gutenberg.org/files/34901/34901-h/34901-h.htm'}
  ]
};
